navpat.py

Currently supporting only 15x5 and 12x5 playground size.
I was tired of editing the `navpat.py` code to settings used during Garden Celebration, when smaller (12x5) demo field was used, so there is new parameter `--playground` with usage like
```
python.exe navpat.py osgar_170608_133319.zip --view --playground 12x5
```
Maybe it should be required parameter? Different name? More generic? (later I suppose variable rectangle size, but so far we played only with two sizes).

Introduce parameter --playground

---

tools/zip2mkv.py

zip2mkv expects zip filepath as argument and creates .mkv file in current directory of the same name. It uses `jpegtrans` and `ffmpeg` which both need to be in path - `jpegtrans` reencodes the jpegs to get rid off the problem with "corrupt jpeg data" and `ffmpeg` is used to create the mkv. It works only on posix system since it uses milliseconds in file timestamps and that is not implemented on windows in `ffmpeg`.

Add tools/zip2mkv.py.

---

tools/logparser2.py

`sensor_gen` now properly implements `selected` where it can contain
any number of sensor names. The output stream is `timestamp`
sorted and contains (`timestamp`, sensor name, `data`).

Allow multiple names in `selected` for tools/logparser2.py

---

tools/logparser2.py

Added `sensor_gen_zip` that reads data from zipfile instead of logs directory.
I am starting to feel the need for some `logging` module that will abstract away if we deal with regular files or files within zipfile (or maybe something else in the future). What do you think?

Read zipfiles in `tools/logparser2.py`.

---

launcher.py
lib/config.py

Use default `config.json` stored in the latest zipped log files (`--config` overrides stored log file). 
This PR can be tested with
```python.exe helloworld.py replay d:\md\osgar\logs\czu170808\osgar_170808_161400.zip```
available [here](http://osgar.robotika.cz/osgar_170808_161400.zip).

Use default config.json stored in zipped log files

---

tools/annot.py

Supports backspace for undo of the last rectangle, ESC for tool termination.
SPACE is reserved for skip of current image. Works for image, directory
and zip files.
Supports both Python 2.7 as well as Python3

Add simple tool for image annotations

---

helper.py
laser.py
tools/parse_laserraw.py

This is the second pull request from recent feature/testYYMMDD related to laser logging and debugging issue with 20s gaps. They were caused by previously turned off laser, but detailed logging of communication could be useful also in the future (and now I would need it also for Velodyne, so some kind of reuse is expected).

Logging of raw laser data + fixup for turning off in navpat

---

config/fill-pattern-15x5.json
config/mapit.json
helper.py
navpat.py

These parts are from forgotten branch test/test171024, when we experiment with automatic cone mapping. The goal is to navigate to the nearest cone in front of you turn 90deg left and repeat.
The second pattern is filling, now with external parameters in config file.
Finally there are two commits related to debug real and mapped cone distances, and removal of unnecessary prints.
p.s. now I see issue in:
`cones = prev_cones  # TODO use robot.prev_cones instead of global variable`
which is no longer valid after Python3 refactoring

Forgotten filling and mapping navpat options

---

lib/logger.py
lib/test_logger.py

This PR is just for "suggestions welcome" - I would like to extend LogReader to filter only some streams, i.e. not all and not a single one. I need it for asserting module input & output, where I need to track two streams. I do not like presented solution much - one argument would be probably sufficient ...??

logger.py - provide option to read from selected streams in parallel

---

config/test-spider-gps-imu.json
config/test-spider.json
drivers/bus.py
drivers/logserial.py
drivers/test_bus.py
drivers/test_logserial.py
test_robot.py

Implemented two thread solution in `LogSerial`, as discussed during #50 . This PR should be merged after #51, because complete removal of `LogSerialOut` is necessary.
Note, that opening two ways communication always means creating two channels in log (which is not necessary for modules like GPS or IMU) - do we want it? Or do we want conditional creation based on configuration?

Change LogSerial to two way communication

---

config/test-canserial.json
osgar/drivers/__init__.py
osgar/drivers/canserial.py
osgar/drivers/test_canserial.py

This is copy and paste from spider.py as discussed in #44 - separation of CAN/serial operations into separate module.
Note, that it is "work in progress", as there are 4 I/O pins needed ("serial_in", "serial_out", "can_in", "can_out) and names, instead of global numbers are getting more critical.

CANSerial - serial line adapter for CAN bus

---

osgar/ro2018.py
osgar/test_ro2018.py

- read goal position from configuration
- integrate EMERGENCY STOP
- correct IMU yaw angle orientation (should be anticlockwise)
- correct IMU by 35deg
- navigate to multiple goals
- turn in place for large angle difference
This is the code tested last Tuesday. In particular IMU offset/calibration has to be reviewed, but it is already loading all waypoints and trying to navigate to one by one. 
Note, that I forgot about timeout=20s so now the program has to be run several times (should I add it as parameter to the configuration file?).
I did not include other two temporary configuration files with waypoints used during testing.

Prepare ro2018.py for the first outdoor test

---

osgar/lib/logger.py

This is simple wrapper into `logger.py` so that recorded data can be displayed/stored (originally serialized by `msgpack`).

logger.py - provide option for data deserialization

---

osgar/ro2018.py

Fixes:
```
Goal at 0.68m
File "ro2018.py", line 225, in <module>
game.play()
File "ro2018.py", line 164, in play
print("Heading %.1fdeg, imu" % math.degrees(geo_angle(self.last_position, go
al)), self.last_imu_yaw)
TypeError: must be real number, not NoneType
```
which was caused by duplicity of waypoints.

ro2018.py - fix print for close positions where geo_angle is None

---

osgar/logger.py
osgar/test_logger.py

This is another cherry-picked PR from Marina boat development. It provides option to select name of stream/channel and newly also to list all names (option `--list`). I would squash it at the end.

Add name options into logger.py script

---

osgar/drivers/canserial.py
osgar/drivers/test_canserial.py

John Deere and Eduro robots need CAN speed 250kb/s and switch for operation and pre-operational
state. This is cherry-picked commit for tomorrow Eduro development.

CANSerial - add configurable speed and CANOpen mode

---

config/test-ip-camera.json
osgar/drivers/__init__.py
osgar/drivers/logsocket.py

This is driver for Eduro IP camera. It uses `urllib.request` as older John Deere. I put the code together with `LogTCP` and `LogUDP` drivers, as I hope for some overlap?? I did a quick test with a local `robotika.cz` to get some image, but I hit the OSGAR limitation :(
```
m:\git\osgar>python osgar\robot.py run config\test-ip-camera.json
Exception in thread Thread-1:
File "D:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\threading.py", line
916, in _bootstrap_inner
self.run()
File "D:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\threading.py", line
864, in run
self._target(*self._args, **self._kwargs)
File "m:\git\osgar\osgar\drivers\logsocket.py", line 100, in run_input
self.bus.publish('raw', data)
File "m:\git\osgar\osgar\bus.py", line 28, in …
```

Add HTTP driver for IP camera

---

osgar/tools/log2video.py

Added extra params for log2video conversion. I dropped the "similarity" feature used for SICK Robot Day video, because as soon as the robot moves similarity is useless (it was OK for stationary "waiting for transporter"). I am not 100% sure about --start-time-sec, if that should automatically cut also the timestamp - again it was used for SICK, that it was clear when 10min match started.
Low priority PR

Extend tool log2video.py with display time, FPS and start time options

---

osgar/drivers/eduro.py
osgar/drivers/test_eduro.py

Exception in thread Thread-1:
File "/root/miniconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/home/robot/git/osgar/osgar/drivers/eduro.py", line 208, in run
for status in self.process_gen(data):
File "/home/robot/git/osgar/osgar/drivers/eduro.py", line 199, in process_gen
self.process_packet(data)
File "/home/robot/git/osgar/osgar/drivers/eduro.py", line 193, in process_packet
self.send_speed()
File "/home/robot/git/osgar/osgar/drivers/eduro.py", line 153, in send_speed
left&0xff, (left>>8)&0xff,
TypeError: unsupported operand type(s) for &: 'float' and 'int'

eduro.py - fix bug with conversion to Python3

---

osgar/drivers/__init__.py
osgar/drivers/logsocket.py
osgar/drivers/test_logsocket.py
osgar/lib/test_config.py

Also provide dynamic TCP connection for port=0
(cherry picked and rebased from `feature/rosproxy` branch)

Extend TCP driver for "server" option (needed for ROSProxy)

---

osgar/tools/log2video.py

This is just a small PR, so that I can easily generate videos from OSGAR ROS Proxy for SubT ...
```
python -m osgar.tools.log2video subt-181216_165025.log -o follow-wall.avi --stream=rosmsg_image.image
```

log2video.py - add stream ID as optional parameter

---

osgar/drivers/logsocket.py

This is "spin-off" from `feature/rosproxy` PR.

TCP Server - add "timeout" parameter for newly created socket

---

osgar/tools/lidarview.py

This is a small pull-request for drawing scale & user zoom in/out

lidarview - draw scale and use +/- for zooming

---

osgar/tools/lidarview.py

https://github.com/pygame/pygame/issues/331 it is a known issue of pygame on linux :disappointed: 
The solution (for now) is to init only display submodule.

pygame sound mixer uses 100% cpu, init only display.

---

config/test-opencv-camera.json
osgar/drivers/opencv.py

This is mainly for Robik, so that we can slow down 15Hz to 4Hz (?) via trivial `self.bus.sleep()`.
(tested on USB camera with 1s sleep, 20s recording of a clock)

Implement sleep for OpenCV driver (in order to slow down FPS)

---

config/test-replay-node.json
osgar/drivers/__init__.py
osgar/drivers/replay.py

This is the first step into logfile reprocessing (i.e. it will generate a new logfile based on old logfile). I realized that even in in ADTF you need special configuration (diagram) for "replay" from "hard disk player" and it is almost straightforward in OSGAR. I also created this PR to let you know, that tried that with goal of reprocessed fusion pose2d for Eduro robot.
Comments are welcome.
Usage:
`python -m osgar.record config\test-replay-node.json --duration 1`
and the result you can see for example via
`python -m osgar.tools.lidarview test-replay-node-190319_052614.log
--poses replay.pose2d --lidar replay.scan --camera replay.jpeg`
So as side-effect it filters and renames streams. :)
Yes, there are many TODOs like reuse of timestamp, proper termination (duration 1s is used to …

Implement ReplayDriver for reprocessing of logfiles

---

osgar/replay.py

Otherwise you get for replay with `-F` parameter:
```
File "D:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\runpy.py", line 193
, in _run_module_as_main
"__main__", mod_spec)
File "D:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\runpy.py", line 85,
in _run_code
exec(code, run_globals)
File "M:\git\osgar\osgar\replay.py", line 79, in <module>
print("maximum delay:", module_instance.bus.max_delay)
AttributeError: 'LogBusHandlerInputsOnly' object has no attribute 'max_delay'
```

bus.py - fix replay with --force parameter

---

examples/subt/report_artf.py

Simple tool for manual artifact report (STIX, April 2019). Tested on sample server from DARPA.
```
martind@martind-Lenovo-G580:~/subt_ws/osgar/examples/subt$ python3 report_artf.py "backpack" 1 2 3
Get Status
b'{"run_clock":25.98,"score":9000,"remaining_reports":6,"current_team":"subt"}'
Report {'x': 1.0, 'y': 2.0, 'z': 3.0, 'type': 'backpack'}
b'{"run":"identifier for the run","url":"some url string","run_clock":3.14,"submitted_datetime":"2019-03-28T05:37:37.291139+00:00","score_change":1,"report_status":"scored","team":"subt","y":2.0,"x":1.0,"z":3.0,"type":"backpack","id":9}'
Get Status
b'{"run_clock":25.98,"score":9000,"remaining_reports":6,"current_team":"subt"}'
```

SubT STIX - add tool for manual artifact report

---

config/subt-e-stop-windows-A24.json
examples/subt/estop.py

Simple test with DARPA E-STOP. I used config "master": true to send the STOP. Tested with two devices and two terminals:
```
M:\git\osgar\examples\subt>python -m osgar.record ..\..\config\subt-e-stop-windo
ws.json --duration 30 --note "connected both, after reset, slave"
WARNING:root:Environment variable OSGAR_LOGS is not set - using working director
y
packet: 15 7e000b8801495300010002000000d7
packet: 15 7e000b8801495300010002000000d7
packet: 15 7e000b8801495300010002000000d7
packet: 15 7e000b8801495300010002000000d7
packet: 15 7e000b8801495300010002000000d7
packet: 15 7e000b8801495300010002000000d7
packet: 15 7e000b8801495300010002000000d7
packet: 15 7e000b8801495300010002000000d7
packet: 15 7e000b8801495300010002000000d7
packet: 15 7e000b8801495300010002000002d5
```
after that it …

SubT - test E-STOP master

---

config/test-pcan.json
osgar/drivers/__init__.py
osgar/drivers/pcan.py

This is implementation of OSGAR Node for USB Peak CAN for Windows. It was used for data collection on robot Kloubak via
```
python -m osgar.record config\test-pcan.json --duration 10
```
And here is corresponding log: http://osgar.robotika.cz/test-pcan-190625_193434.log
The next plan is to use/test/create driver for Linux, and later replace OSGAR CAN messages with 3-tupple [address ID, data, flags].
Note, that only data collection was tested.

Implement Peak CAN driver

---

osgar/bus.py
osgar/test_bus.py

Workaround for issue with replay `subt.py` of `pose3d` containing lists of floats.

bus.py - introduce almost_equal() for replay of float data

---

osgar/drivers/__init__.py

The comma at the beginning is probably not PEP8 and for example PyCharm
permanently reformates this file - hopefully fixed.

Reformat drivers/__init__.py

---

osgar/tools/log2apriltag.py

Usage in bash:
```bash
python -m osgar.tools.log2apriltag /path/to/directory/**/*.log
```
use `shopt -s globstar` to turn on recursive directory expansion of **.

Run apriltag detector on a list of log files.

---

osgar/tools/log2apriltag.py

For eduro logs I recommend to run it with `2>/dev/null` to dump the `Corrupt JPEG data: 11 extraneous bytes before marker 0xd9` messages.
Continue to the next detection by pressing any key, exit by pressing `Esc`.

Add --gui and --margin, show area.

---

osgar/record.py

record: Allow multiple config files on cmdline.

---

subt/artifacts.py
subt/test_artifacts.py

It is still valuable to have info, that in particular image an artifact was detected. It is position
is ignored and set to (0, 0).

artifacts.py - workaround for missing scan

---

subt/report_artf.py

For example use "S 0 0 0" to report Survivor at position (0, 0, 0)

report_artf.py - use single letter for reporting artifacts

---

.travis.yml
examples/sick2018/sick2018.py
osgar/go.py
osgar/lib/config.py
osgar/lib/test_config.py
osgar/record.py
osgar/replay.py
osgar/ro2018.py
osgar/test_record.py
osgar/turn.py
subt/main.py

With this change any module (including the application) can be replayed
using generic `replay` facility (one step closer to unified launcher).
Fixes #251

Move `application` handling from `record` to `config.load`.

---

osgar/logger.py

Running
python -m osgar.logger file.log --format '{sec}'
outputs just timestamps formatted as seconds. Or you can even use
--format "{sec} {data[:10].hex()}"
to output the first 10 bytes of data formatted as hex.

Allow custom format output.

---

osgar/bus.py
osgar/drivers/cortexpilot.py
osgar/drivers/eduro.py
osgar/drivers/gps.py
osgar/drivers/imu.py
osgar/drivers/logserial.py
osgar/drivers/logsocket.py
osgar/drivers/lora.py
osgar/drivers/lord_imu.py
osgar/drivers/rosproxy.py
osgar/drivers/sicklidar.py
osgar/drivers/spider.py
osgar/drivers/test_cortexpilot.py
osgar/drivers/test_eduro.py
osgar/drivers/test_imu.py
osgar/drivers/test_logserial.py
osgar/drivers/test_logsocket.py
osgar/drivers/test_lora.py
osgar/drivers/test_lord_imu.py
osgar/drivers/test_rosproxy.py
osgar/drivers/test_sicklidar.py
osgar/drivers/test_spider.py
osgar/record.py
osgar/test_bus.py

Our Bus API was very leaky abstraction. All tests were touching directly the insides of BusHandler so it was nearly impossible to refactor the implementation without editing all of the tests.
This PR introduces new API aimed at fixing the problem with the leaking abstraction. For example usage please see
https://github.com/robotika/osgar/blob/da62ba8bb0aeec9752379d8b8b6a442791cc7ddb/osgar/record.py#L21-L27
or any of the refactored test cases.
While I was going over the test cases anyway, I fixed also #161 . Oh, and I nuked the `tcp_point_data` compression. Is it still used somewhere?
I realize it is fairly large changeset but it should leave us better prepared for the future (without it, there is no chance to try `trio` for example as that requires adjustments to the bus implementation).

Refactor Bus API

---

config/tank-maria.json
osgar/drivers/__init__.py
osgar/drivers/tankmaria.py
osgar/drivers/test_tankmaria.py

- add MariaTimer
- ASCII protocol "<left> <right> <LED>\n"
- parse encoders
- handle invalid initial data
- test speed as parameter for PWM
- fix bus.register() after refactoring

Add driver and configuration for tank Maria

---

osgar/drivers/lora.py

```
M:\git\osgar>python subt\control_center_qt.py
WARNING:root:Environment variable OSGAR_LOGS is not set - using working director
y
Running self-detection... waiting for b'alive-281016'
recording started
pause mission
Exception in thread Thread-4:
File "D:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\threading.py", line
916, in _bootstrap_inner
self.run()
File "D:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\threading.py", line
864, in run
self._target(*self._args, **self._kwargs)
File "M:\git\osgar\subt\control_center_qt.py", line 202, in run
self.view.robot_status.emit(robot_id, pose2d, status)
TypeError: View.robot_status[int, list, bytes].emit(): argument 3 has unexpected
type 'str'
```

lora.py - fix hacked state to be bytes instead of str

---

osgar/bus.py
osgar/lib/serialize.py
osgar/lib/test_serialize.py

- controlled via names with suffix :null and :gz

bus.py - no_output and compressed_output

---

osgar/tools/log2map.py

The `log2map` tool at the moment only draws the `pose2d` and is designed to get quick overview of the log.

Add tools/log2map.py for fast log preview

---

osgar/drivers/lord_imu.py

LORD IMU sometimes also supports GPS output (model 45)

lord_imu.py - fix bug in register (missing 'gps_position')

---

osgar/drivers/logsocket.py

There are 4 devices connected over the Ethernet and it is not clear which one failed if you see:
```
(base) root@voyage:/home/robot/git/osgar# python -m subt run config/kloubak2-subt-estop-lora.json --side right --note "test v hale K2, master po Virtualu"
Kloubak mode: DriveMode.ALL num_axis: 2
File "/root/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/root/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/robot/git/osgar/subt/__main__.py", line 2, in <module>
main()
File "/home/robot/git/osgar/subt/main.py", line 916, in main
record(cfg, prefix)
File "/home/robot/git/osgar/osgar/record.py", line 52, in record
with Recorder(config=config['robot'], logger=log) …
```

logsocket.py - report timeout source

---

config/eduro-subt-estop-lora-wifi.json
config/eduro-subt-estop-lora.json
config/kloubak2-subt-estop-lora.json
config/kloubak3-subt-estop-lora.json
examples/sick2018/sick2018.py
osgar/drivers/logzeromq.py
osgar/drivers/rosproxy.py
osgar/drivers/test_logzeromq.py
osgar/drivers/test_rosproxy.py
osgar/record.py
osgar/ro2018.py
subt/control_center_qt.py
subt/main.py

After all modules are joined, all running threads are listed
and reported to console as an error.
It should help in the cases when SIGINT is ignored due to the main thread being stuck in `thread.join` call.

record: add timeout to join call

---

subt/report_artf.py

Only one shot is used and optional arguments are commented out to allow easily negative numbers
(not to be misinterpreted as options)

subt/report_artf.py - update and fix

---

osgar/drivers/rosmsg.py
subt/script/mobos-view.bat

tested on sample data from MOBoS

drivers/rosmsg.py - support also uint16 RGBD depth data from ROS

---

subt/artifacts.py

Probably this is not the correct solution but at least it identifies the problem. The survivor detection was working for virtual track only. Tested with logs kloubak2-subt-estop-lora-jetson-200224_175001.log and kloubak2-subt-estop-lora-200220_051641.log. Number of false detection were approx 30 (first log, run 3).

Enable "survivor" detection

---

subt/docker/loadtest/Dockerfile
subt/docker/loadtest/loadtest_entrypoint.bash
subt/docker/loadtest/main.py

- Allow iteration count setting from cmdline.
- Sleep at the end. Don't call /subt/finish immediately, sleep for a
while to give a chance to parallel runs to finish as well. Intended for
cloudsim tests.
- Startup according to ROS images:
https://github.com/osrf/docker_images/blob/460ddc4707530c2179788e2100d5c624cf2af3d7/ros/melodic/ubuntu/bionic/ros-core/Dockerfile
https://github.com/osrf/docker_images/blob/460ddc4707530c2179788e2100d5c624cf2af3d7/ros/melodic/ubuntu/bionic/ros-core/ros_entrypoint.sh

Implement load testing for cloud sim.

---

osgar/logger.py
osgar/record.py
osgar/test_logger.py
osgar/test_record.py

Be a proper program according to https://www.cons.org/cracauer/sigint.html.
When `osgar.record` is called from a script and Ctrl+C is pressed, shell
now knows everything should quit. Workaround
https://bugs.python.org/issue1054041 which is fixed only in python 3.8.

osgar.record: make SIGINT suicide

---

.github/workflows/python-ci.yaml

Since Travis is not showing UI on github for an unknown reason, I use that as an excuse to setup Github Actions. The added benefit will be tests on Windows.

Add github actions for CI.

---

osgar/lib/quaternion.py
osgar/lib/test_quaternion.py

`osgar.lib.quaternion.rotate_vector` still assumed the old convention where `w` was first, not last.

quaternion: fix rotate_vector

---

.dockerignore
.gitignore
subt/docker/run.bash
subt/script/sim.bash

When a simulation is run locally using the `subt/script/sim.bash` file, the ignition logs (particularly the `state.tlog` file) are saved to a directory inside the checkout. The `state.tlog` file is useful for getting the true positions of the robots that are to be used for localization validation.
If you use `sim.bash` and want to keep it without the addition of this feature, I can add a separate script file.

sim.bash: use volume to save simulation logs.

---

osgar/drivers/rosmsg.py
subt/zmq-subt-x2.json

It runs, but I have not been able (yet) to verify the contents.

rosmsg: Publish orientation quaternion from std_msgs/Imu.

---

subt/docker/robotika/ros_proxy_node.cc

During the last refactoring a regression has been introduced - the maximum size limit of `robot_data` was not honored.
The code in the PR limits the data sent to `robot_data` topic, resulting in this last message in the stream `rosmsg.sim_time_sec` to be `1:01:02.515707 19 3813` and limiting the size to approx 2GB. BTW: the simulation still continues past the 3600s mark.

ros_proxy_node: limit robot_data size

---

subt/script/sync.sh

Significantly speeds up repeated rebuilds inside running docker
container.

sync.sh: don't copy CMakeLists.txt if not changed.

---

osgar/logger.py
osgar/test_logger.py

Use as `logger <file> --stream <steam> -- format "{walltime}" to get
readable representation of calendar time or
`logger <file> --stream <steam> -- format "{walltime.timestamp()}" to
get unix timestamp value.
Necessary feature for comparing real time from cloudsim ROS and osgar logs.

osgar.logger: add walltime to format string

---

subt/zmq-subt-x2.json

When zmq sends data fast enough the `slot_raw` function is called over and over never giving chance other threads. This happens intermittently but can have fatal consequences - I've found one logfile where this kept going for 44s. With this change I was able to once get 1 point on cloudsim with X0F100L robot for the first time.

subt/zmq-subt-x2.json: send data to receiver.raw instead of slot

---

subt/docker/robotika/Dockerfile
subt/docker/robotika/entrypoint.bash
subt/script/sync.sh

Speeds up builds and makes the resulting docker image much smaller.

Use devel space instead of install space.

---

subt/docker/robotika/ros_proxy_node.cc

Waiting for one /clock message is not enough because gazebo has clock
hickups during startup. Sleeping 1 simulated second takes about 20 walltime
seconds on my computer. 
Without this change a false positive error is detected when checking
delays between publish|listen because log filename is sent right away
and then 20s wait time for first clock message.

ros_proxy_node: wait for full simulation startup

---

osgar/drivers/logzeromq.py

It is useful for `rosmsg` development to save also ROS data received from ZeroMQ.
(this is 1/4 PR for `feature/moon-ver0`)

logzeromq.py - add conditional log saving based on config['save_data']

---

osgar/test_bus.py

The error `AssertionError: 255.85899999999998 not greater than or equal to 255.859`
https://github.com/robotika/osgar/pull/427/checks?check_run_id=591742038
was probably caused due to rounding or different representation of time

osgar/test_bus.py - increase robustness of the test_alive

---

subt/docker/robotika/run_solution.bash

While short in lines, this change seems to have a really great impact. I am still running more tests on cloudsim but the initial testing suggests major improvement wrt performace and latency.
The problem (as discussed over emails) is openblas going crazy creating many threads trying to parallelize something, with the only result of taking all available CPUs and getting the results significantly slower. On my 4C8T machine the difference in effectiveness is about 20 times better (faster by factor of 2.6 and using only 1 instead of 8 CPUs).

run_solution: OMP_NUM_THREADS=1

---

subt/rosbag2log.py

I've hidden what I considered debug output behind `--verbose` flag. We can leave it like that or remove it completely. I've also added output which files are being extracted or skipped due to missing `-a` option.

subt.rosbag2log: hide debug output

---

subt/docker/robotika/ros_proxy_node.cc

Tested on cloudsim. Creates 3 files in downloadable tar. The last one ends with `.active`.

ros_proxy_node: increase log size to 3GB

---

subt/main.py

There have been many changes merged that deserve further testing. Some
notable ones include:
- 3GB log files on cloudsim
- OMP_NUM_THREADS=1 to stop openblas from spinning up a crazy number of threads
- send data to receiver.raw instead of slot_raw which prevents some CPU
starvation (sometimes receiver was the only thread running for 44 sec)
- maximum delay over 0.1s of listen-publish pairs is logged as error
- upgraded dependencies (most notably opencv 4.2.0)
- zmq receive in ros_proxy_node has its own thread (preventing dropping
of set speed commands)
- ros_proxy_node is built with optimizations (release build)
- app.pose3d implemented for virtual track
- sending log to robot_data in ros_proxy_node has its own thread

subt.main: set Ver62

---

.github/workflows/python-ci.yaml

When it gets stuck, we should be notified earlier than after 6 hours.

.github/workflows: set timeout-minutes to 5

---

osgar/record.py
osgar/test_record.py

Signal can be received while inside print()
https://bugs.python.org/issue24283

osgar.record: print() is not reentrant

---

osgar/drivers/rosproxy.py
osgar/drivers/test_rosproxy.py

At last, I've managed to reproduce the problem locally:
<pre>  File &quot;/home/zbynek/osgar-ws/devel/osgar/drivers/test_rosproxy.py&quot;, line 119, in test_usage
master.shutdown()
File &quot;/home/zbynek/osgar-ws/devel/osgar/drivers/test_rosproxy.py&quot;, line 89, in shutdown
s.request_shutdown()
File &quot;/usr/lib/python3.6/xmlrpc/client.py&quot;, line 1112, in __call__
return self.__send(self.__name, args)
File &quot;/usr/lib/python3.6/xmlrpc/client.py&quot;, line 1452, in __request
verbose=self.__verbose
File &quot;/usr/lib/python3.6/xmlrpc/client.py&quot;, line 1154, in request
return self.single_request(host, handler, request_body, verbose)
File &quot;/usr/lib/python3.6/xmlrpc/client.py&quot;, line 1167, in single_request
resp = http_conn.getresponse()
File …

fix rosproxy test failure

---

subt/docker/robotika/rosconsole.config

We primarily need info about dropped messages so disabling this lowers the
cognitive load.

rosconsole: disable roscpp_internal messages.

---

moon/scout1.json

This was copy and paste of SubT but in Moon the images are at 10Hz and lidar scans are also at 10Hz. Due to interference it looked like that several images are dropped in lidarview.
p.s. I am not sure if we still want to have downsampling in SubT, potentially degradating capability (before it was reduced for performance)

moon/scout1.json - remove lidar downsampling

---

subt/docker/base/Dockerfile
subt/docker/cudatest/Dockerfile
subt/docker/cudatest/cloudsim_run.py
subt/docker/cudatest/cudatest3.py
subt/docker/cudatest/cudatest_entrypoint.bash
subt/docker/cudatest/rospywrapper.py
subt/docker/robotika/entrypoint.bash

Output when running locally:
<pre>$ (feature/cuda+torch+tensorflow) ./subt/docker/run.bash cudatest 
Waiting for rosmaster
4.0509250164 [&apos;/roslaunch/uris/host_larsa__33405&apos;, &apos;/run_id&apos;]
4.49758291245 [&apos;/roslaunch/uris/host_larsa__38057&apos;, &apos;/roslaunch/uris/host_larsa__33405&apos;, &apos;/rosdistro&apos;, &apos;/rosversion&apos;, &apos;/run_id&apos;]
4.55253100395 [&apos;/roslaunch/uris/host_larsa__38057&apos;, &apos;/roslaunch/uris/host_larsa__33405&apos;, &apos;/rosversion&apos;, &apos;/run_id&apos;, &apos;/enable_statistics&apos;, &apos;/robot_names&apos;, &apos;/use_sim_time&apos;, &apos;/world_name&apos;, &apos;/rosdistro&apos;]
<font color="#4E9A06">[DEBUG] [1588579513.300989, 0.000000]: init_node, name[/cudatest], pid[1]</font>
<font …

Add cuda-based subt-base image with cudatest image.

---

subt/docker/robotika/run_solution.bash

Osgar is handling SIGINT correctly now and roslaunch escalates to SIGTERM
after timeout if the nodes do not react on SIGINT. Using SIGINT has the
advantage of giving everyone the chance to do a propper shutdown (like
closing the log file).

run_solution.bash: use SIGINT instead of SIGTERM.

---

subt/docker/cudatest/cudatest_entrypoint.bash

If the image is run on debian host, it fails due to not being able
to find all required libraries.

cudatest: add ldconfig

---

subt/docker/base/Dockerfile
subt/docker/cudatest/Dockerfile

Results in 2GB space savings (7GB instead of 9GB).

subt-base: switch base image from devel to runtime

---

osgar/logger.py
osgar/record.py
subt/main.py

When the log filename is set from outside, it is known to the startup script. This script can then also start a separate "log uploader" node to upload the log to `robot_data`. Then this part no longer needs to be inside `ros_proxy_node.cc` and can be independent (it can even be in python2 using rospy if we wish). `LogWriter` already had this capability so it was just a matter of exposing it.

subt: Allow setting log filename from cmdline.

---

.github/workflows/python-ci.yaml

Python fails to autodetect it runs in unicode environment when run in Github CI.

github-ci: set utf-8 encoding on console output

---

subt/local_planner.py

The PR contains no code changes. The motivation for the change is to make it clearer what the arguments actually mean - "start" is the angle of the first sample in the scan and "end" is the angle of the last sample. The original names were somewhat confusing to me. The names with the default values make it clear that the default scan is 270 degrees wide and goes from right to left (from -135 to +135).

subt.local_planner: rename scan_{right,left} to scan_{start,end}

---

test.py

With these changes we can run `./test.py subt` (to execute all tests inside `subt` package) while inside `subt` we have `test_something.py` where inside is 
```python
from . import something
```
It is the equivalent of running 
```
python -m unittest discover --top-level-directory . --start-directory subt
```

test: allow for relative imports in tests

---

osgar/bus.py
osgar/test_bus.py

Fixed comparison of inf values (from Moon project, where radius=inf encodes straight line)

Handle correctly almost_equal() for inf values

---

osgar/tools/lidarview.py

Frantisek asked me for `lidarview` extension to draw detection boxes for debugging Moon navigation. This feature could be also useful for SubT as long as we add bounding boxes into logfile [name, x, y, width, height].
Example:
Note, that it is not perfect as the streams are not "grouped". Also detection in multiple images (say left and right camera) is not handled [BTW it is probably the reason for this double rectangle]

lidarview.py - add --bbox option to draw object bounding box

---

osgar/drivers/gps.py
osgar/drivers/test_gps.py

Workaround for nonsensical data received from GPS (usually during gps start).

driver gps: add "try" to "str2ms" function

---

osgar/bus.py
osgar/drivers/realsense.py
osgar/lib/serialize.py
osgar/lib/test_serialize.py

For the work using zeromq for communication I need to separate compression from the serialization (to be able to compress data going to log only). 
I also decouple compression from numpy arrays - numpy arrays used to be compressed unconditionally which has caused confusion (at least for me) several times already.
I've kept the deserialization code backward compatible so that it is able to read older logs where numpy arrays are compressed always.

osgar.lib.serialize: refactor compress out from serialize

---

osgar/logger.py
osgar/test_logger.py

For the work using zeromq for communication I need to separate timedelta serialization and parsing from log reading/writing so I can reuse the same serialization for network communication. So I have picked up all timedelta handling scattered over osgar.logger a factored it out into separate functions.

osgar.logger: refactor timedelta handling

---

osgar/drivers/rosmsg.py
osgar/logger.py
subt/docker/robotika/run_solution.bash
subt/main.py
subt/ros/proxy/ros_proxy_node.cc
subt/ros/proxy/sendlog.py
subt/script/bridge.bash
subt/script/devel.bash
subt/script/sim.bash

There are several not that related changes here but I felt they are so small they might not be worth their own PR (given that we already have several PR open).
The main goal was to move logsending out from ros_proxy_node.cc into a separate rospy-based node because the "deep hack" in rosmsg.py was not working for zmq-based communication (not surprisingly).

Move logsending out from ros_proxy_node.cc into sendlog.py

---

osgar/record.py
osgar/test_zmqrouter.py
osgar/zmqrouter.py
subt/main.py
test.py

`zmqrouter.record` can start all modules as separate processes and route ZeroMQ messages among them - all without changing a single line inside the modules. In the future modules can be implemented in different languages (python2+rospy or rospp or anything else supporting ZeroMQ) and be native parts of osgar. We are also no longer bound by python GIL - osgar can now use all 16 cores in cloudsim.
The main process creates `zmq.ROUTER` socket and modules use `zmq.REQ` socket. All message
buffers are in the main process - each module is always handling only a single message. This is the basic control flow:
- router is created (socket is bound and ready to accept messages)
- modules are started one by one and each blocks within `bus.register` call where it advertises what outputs it has
- …

osgar.zmqrouter: run modules as processes

---

osgar/lib/quaternion.py
osgar/lib/test_quaternion.py

Since #565 uses matrices for rotations we need to be able to go back and forth between matrices and quaternions.

osgar.lib.quaternion: add from_rotation_matrix

---

osgar/tools/lidarview.py

--title takes a comma-separated list, will display info from all listed streams within the titlebar
also, all bboxes reported between two consecutive images will be shown within the next image

allow lidarview to show multiple streams within titlebar and multiple bounding boxes within images

---

osgar/tools/lidarview.py

Lidarview window is now resizable by dragging its edges and corners. The content of the window should fill the available space accordingly.

make lidarview window resizable

---

osgar/replay.py

... otherwise SubT localization module cannot be replayed ... minor fix, thanks m.

osgar/replay.py - fix replay of modules without "init" config section

---

subt/docker/robotika/run_solution.bash
subt/main.py
subt/teambase.py
subt/test_teambase.py

Yet another SubT (dangerous) PR ... we could use TEAMBASE to terminate all robots, i.e. when teambase ends everything ends ... I am not sure if it is safe for the competition (the answer is NO), but for testing on AWS it can speedup cycle time (and make logs reasonable).
Note, "minor" detail, that `teambase.py` does not parse "robot_name", because it is not receiving "origin" ... ideas welcome ...

SubT - allow teambase to kill all robots

---

osgar/lib/config.py
osgar/lib/test_config.py

osgar.lib.config: allow overrides in dict merging

---

subt/cloudsim2osgar.py
subt/zmq-subt-x4.json

This is an alternative implementation of #608.
It also adds the infrastructure to enable per configuration topics.
Tested with `robotika_x2` and `ssci_x4_sensor_config_2` where I have this in the log:
<pre>36             rospy.rot    108039 | 11618 | 143.6Hz
37             rospy.acc     90995 | 11618 | 143.6Hz
38     rospy.orientation    429866 | 11618 | 143.6Hz
39        rospy.top_scan     23210 |  2321 |  28.7Hz
40     rospy.bottom_scan     23210 |  2321 |  28.7Hz
41       depth2scan.scan    424861 |   221 |   2.7Hz
42             vo.pose3d     58212 |   882 |  10.9Hz
</pre>

subt.cloudsim2osgar: log top and bottom scan on drone

---

subt/cloudsim2osgar.py
subt/push.py
subt/zmq-subt-x2.json

Implements sending messages from `osgar` to `cloudsim`/`ROS`. Uses `PUSH`/`PULL` sockets from `zmq`. Serializes using msgpack. Supports arbitrary channel names.

subt.{cloudsim2osgar,push}: add osgar->cloudsim direction

---

osgar/bus.py

Fixes following error:
```
$ python -m osgar.replay --module app d:\logs\aws\ver74rc1s2b\T\aws-ver74rc1s2b-T300.log
original args: b"['/osgar-ws/src/osgar/subt/teambase.py', '/osgar-ws/src/osgar/subt/zmq-subt-teambase.json', '--robot-name', 'T300', '--log', '/osgar-ws/logs/zmq-subt-teambase-2020-09-25T18.41.16.log', '--note', 'run teambase']"
Exception in thread Thread-1:
File "C:\SDK\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\threading.py", line 916, in _bootstrap_inner
self.run()
File "D:\osgar\osgar\node.py", line 40, in run
self.update()
File "D:\osgar\subt\teambase.py", line 31, in update
handler(getattr(self, channel))
File "D:\osgar\subt\teambase.py", line 24, in on_sim_time_sec
self.request_stop()
File "D:\osgar\osgar\node.py", line 45, in …
```

osgar/bus.py - fix missing shutdown() for replay

---

subt/main.py

File "D:\osgar\subt\main.py", line 581, in update
self.stdout(timestamp, '(%.1f %.1f %.1f)' % self.xyz if self.xyz is not None else '(xyz=None)', sorted(self.stat.items()))
TypeError: must be real number, not list
This bug showed in test of `ver74rc1` when the drone `B30F100L` did not take off.

subt/main.py - fix crash for self.xyz as received list instead of tuple

---

subt/breadcrumbs.py
subt/cloudsim2osgar.py
subt/main.py
subt/test_breadcrumbs.py
subt/zmq-subt-x2.json

This is the very first attempt to deploy [breadcrumbs](https://github.com/osrf/subt/wiki/api) from robot Freyja (config 2).
It was tested on "simple cave 1" (ver75rc1) but with error of deploying all breadcrumbs within first minute (fixed). Nevertheless the log from teambase showed already extended range reported every 10s by all robots:
The range was extended only by a little as the breadcrumbs were not correctly deployed (rerun of ver75rc2 should be available within 1hour).

Indroduction of breadcrumbs

---

osgar/logger.py
subt/tools/validator.py

This simplifies calling of validator in cases when 
- the `state.tlog` is in current directory
- there is only one osgar logfile in current directory
The workflow to analyze cloudsim run is:
- download all tar.gz log to a dedicated directory
- run `python -m subt.rosbag2log <filename>.tar.gz` for each of them
- run `python -m subt.tools.validator`
I plan to lift the restriction on a single osgar logfile and process all logfiles sequentialy in next PR.

subt.tools.validator: add autodetection of filenames in curdir

---

subt/tools/validator.py

This is the sequel announced at #645. The diff looks big but it is mostly indentation change due to the loop over all logfiles.
Example outputs:
<pre>Ground truth count: 41053
Processing logfile: aaa.log
Autodetected name: X200L
Trace reduced count: 465
Ground truth seconds: 492
Maximum error: 3761.30m -&gt; FAIL
Processing logfile: zmq-subt-x4-2020-09-30T10.43.12.log
Autodetected name: X200L
Trace reduced count: 465
Ground truth seconds: 492
Maximum error: 3761.30m -&gt; FAIL
</pre>
<pre>Ground truth count: 35297
Processing logfile: zmq-subt-x4-2020-09-30T10.23.30.log
Autodetected name: X200L
Trace reduced count: 438
Ground truth seconds: 492
Maximum error: 1.08m -&gt; OK
</pre>

subt.tools.validator: process all logfiles in curdir

---

subt/tools/ignstate.py

Another bit to improve the ergonomics of log analysis. The sequence of possible commands in the directory with the logfiles can now include
```
python -m subt.tools.ignstate [-o]
```
with optional `-o` to open the resulting png.

subt.tools.ignstate: look for `state.tlog` in curdir

---

subt/rosbag2log.py

There are 2 commits
- the first one just moves code around without any changes
- the second one is the actual implementation
The workflow with this code (and with #646) is the following:
- open cloudsim site
- open browser preferences, find the option to set default download directory and set it to a newly created directory
- click on all logfiles from a single simulation run and wait until the files appear in the directory selected above
- in terminal, change to that directory and run in sequence:
* `python -m subt.rosbag2log`
* `python -m subt.tools.validator`
Now you should see if any of the robots got lost :v: 
Couple of notes:
- the `-a` option does not make sense - I have never ever wanted an incomplete log file - so my proposal is to remove the option in its entirety and just …

subt.rosbag2log: process all tar files in curdir 

---

subt/tools/validator.py

Example output:
<pre>$ python -m subt.tools.validator
Ground truth count: 153982
Processing logfile: aws-jl001cvrc1q-A1300L.log
Autodetected name: A1300L
Autodetect pose3d stream: offseter.pose3d
Trace reduced count: 1253
Ground truth seconds: 1524
Maximum error: 31.04m -&gt; FAIL
Processing logfile: aws-jl001cvrc1q-T1500.log
Autodetected name: T1500
skiping teambase
Processing logfile: aws-jl001cvrc1q-C20W1200L.log
Autodetected name: C20W1200L
Autodetect pose3d stream: localization.pose3d
Trace reduced count: 1272
Ground truth seconds: 1524
Maximum error: 225.48m -&gt; FAIL
Processing logfile: aws-jl001cvrc1q-D30W1200R.log
Autodetected name: D30W1200R
Autodetect pose3d stream: localization.pose3d
Trace reduced count: 1503
Ground truth seconds: 1524
Maximum error: 471.73m -&gt; FAIL …

subt.tools.validator: skip teambase, autodetect pose3d stream

---

subt/breadcrumbs.py
subt/test_breadcrumbs.py
subt/zmq-subt-x2.json

This is preliminary step to place breadcrumbs more reasonably, i.e. instead of time interval it takes into account 3D distance. The `self.locations` should be later exchanged among all robots, so they will not place breadcrumbs where not needed. The location info could be later used also by teambase for filtering false artifacts or robot relocalization ... one day.
Note, that 30m is just wild guess and need evaluation. It would require to run at least 2 robots (TEAMBASE and Freyja config2) to be able to see it - I am adding @frantisekbrabec if he wants to try to find more suitable value (based on different worlds).

SubT Breadcrumbs deploy based on distance

---

subt/tools/test_validator.py
subt/tools/validator.py

Example output:
```
Ground truth count: 153982
Processing logfile: aws-jl001cvrc1q-A1300L.log
Autodetected name: A1300L
Autodetect pose3d stream: offseter.pose3d
Trace reduced count: 1253
Ground truth seconds: 1524
sim_time_sec:   800, error:  1.04m, distance:  100.42m from origin, path:  755.60m
sim_time_sec:   893, error:  2.09m, distance:  125.43m from origin, path:  848.85m
sim_time_sec:  1273, error: 11.46m, distance:  225.33m from origin, path: 1234.28m
Maximum error: 31.04m -> FAIL
Processing logfile: aws-jl001cvrc1q-T1500.log
Autodetected name: T1500
skiping teambase
Processing logfile: aws-jl001cvrc1q-C20W1200L.log
Autodetected name: C20W1200L
Autodetect pose3d stream: localization.pose3d
Trace reduced count: 1272
Ground truth seconds: 1524
sim_time_sec:   125, error:  1.00m, …
```

subt.tools.validator: show more info about position quality

---

osgar/lib/loop.py
osgar/lib/test_loop.py
subt/main.py
subt/zmq-subt-x4.json

Increase of tilt/roll limits to max and integration of loop detector (just print). Note, that the replay visibly slowed down so we may need to move loop detector to separate process? Also instead of print we may trigger action similar to virtual bumper? (for now)
Or we can at least publish "loop", which would oscillate True/False, i.e. report on change? If we extract loops after `pose3d` update, then it can be really separate node. Yes, there can be revision after "virtual obstacles" are implemented.

Increase of tilt/roll limits to max and integration of loop detector

---

subt/radio.py
subt/test_radio.py
subt/zmq-subt-x2.json
subt/zmq-subt-x4.json

This is the first step of refactoring LoRA - cut bits which should be SubT Virtual specific.
The LoRA should be universal driver for sending small packets over long range radio. In SubT Virtual the packets are much bigger and can be send much more frequently. Also we need "virtual specific" functionality.
This PR creates `subt/radio.py`, which implements the same functionality, which currently also is in `subt/drivers/lora.py`:
* broadcast robot position every 10s
* broadcast internally received artifacts one by one
* publish externally received artifacts as "newly detected" (`artf_xyz`)

SubT refactoring LoRA into subt/radio

---

subt/tools/ignstate.py
subt/tools/validator.py

`read_poses` now returns robot positions and breadcrumbs positions (since it returns xyz and not pose, it is probably misnamed... oh well).
The positions are now `namedtuple` supporting both xyz attr and [0], [1], [2] indexing. The protobuf types are not leaked outside anymore.

subt.tools.ignstate: extract also breadcrumbs

---

subt/tools/submit.py

I have cleaned up a tool I was using locally for some time already. It has not really been tested much after the refactoring since a valid test requires submitting a new run.
The usage is as follows:
1. create a `run.toml` file
2. run `python -m subt.tools.submit [-n]` from the directory with `run.toml`
Example toml file for the recent drone relay run:
```toml
world = "cs2"
timeout = 2300
image = "ver81rc1"
[robots]
A1050L = "drone"
B300W900L = "drone"
C900W600L = "drone"
```
Example output:
```
world:   Cave Simple 2
image:   200670743174.dkr.ecr.us-east-1.amazonaws.com/subt/robotika:ver81rc1
simname: ver81rc1cs2r1
robots:  
A1050L: SSCI_X4_SENSOR_CONFIG_2
B300W900L: SSCI_X4_SENSOR_CONFIG_2
C900W600L: SSCI_X4_SENSOR_CONFIG_2
T2300: TEAMBASE
======= not really submiting =======
...
```
A …

subt.tools.submit: to ease submitting runs to cloudsim

---

subt/tools/ignstate.py
subt/tools/startfile.py
subt/tools/validator.py

I always close the opencv viewer with Alt+F4 which leaves me with no choice but to cancel the whole run. This makes it consistent with what `ignstate -o` does.

subt.tools.validator: open ground truth pic with system viewer

---

osgar/drivers/rosmsg.py
osgar/drivers/test_rosmsg.py
subt/cloudsim2osgar.py
subt/drone.py
subt/ros/robot/launch/x4.launch
subt/test_drone.py
subt/zmq-subt-x4.json

This is copy & paste from ROS module to OSGAR to fly with X4 and height control with top/bottom lidars.
The test images have prefix `ver82fly` (first test `81a94f48-cf57-4355-ae1a-a8f0108df04e`)
Known issue is that `rosmsg.py` automatically publishes commands independently of received data - this is problem for drone because we do not want to send any until wait time elapsed.
In the "merge chain" we may need feature variable height control - @jisa do you have an example where drone is trapped in the hole and never returns because of steep walls? (until that the functionality is equal (or worse due to start) to ROS node).
Issues/TODO:

SubT X4 control height via OSGAR

---

subt/ros/robot/launch/freyja.launch
subt/ros/robot/launch/x4.launch

This Kalman change to X4 looks much better than attempt in tested before in https://github.com/robotika/osgar/pull/680
(see run `ver82quat1`, `e0b1ce5a-d6f3-4d57-af26-6d5d6eae3184`)

launch/x4.launch - use velocities instead of relative position change

---

subt/ros/proxy/pose_from_artifact_origin.cc

just to be sure that it does not block communication and reporting artifacts. The precision should go from nm to mm.

Reduce origin query "GPS" to 5Hz

---

subt/cloudsim2osgar.py

http://wiki.ros.org/rospy/Overview/Logging
rospy does not support `logerror()` only `logerr()`

Fix reporting ROS error in cloudsim2osgar.py

---

subt/cloudsim2osgar.py
subt/docker/robotika/run_solution.bash
subt/ros/proxy/wait.py
subt/tools/run.py

Changes:
- As we had a special routine to wait for master, we now have a similar one for waiting for bridge.
- The bridge creates subscribers and publishers as it makes connections with the simulation so this transitively waits for the simulation to start up. There is also less stress on the computer during startup since there is less parallelization.
- It also improves the detection of breadcrumb abilities. 
- The robot config detection is now in one place only - `wait.py`. I imagine that once cloudsim adds robot config to rosparam, we can further simplify.
Tested with freyja 2 only so far.

Rework startup to increase robustness.

---

subt/tools/ignstate.py

Motivation: better overview of how many artifacts of each type is present
Urban worlds have different number of each type and in unsorted list it was really hard to make sure I did not overlook some.
p.s. yes, this PR is way to trivial, sorry for that ...

list artifacts sorted by name (subt.tools.ignstate)

---

subt/tools/run.py

Removes confusing networks left behind the simulation, shown when you run `docker network list`.

subt.tools.run: prune networks on exit

---

subt/docker/gui/Dockerfile
subt/docker/gui/entrypoint.bash

Running ./subt/docker/run.bash gui opens gazebo gui and connects it
to a simulation started by subt.tools.run. It should be able to connect
over a local network (the simulation and gui running on different
computers).

subt/docker/gui: start gazebo gui in a container

---

subt/tools/submit.py

There are now Tunnel and Cave circuits competition worlds available on CloudSim. Note, that link to 
https://pkg.go.dev/gitlab.com/ignitionrobotics/web/cloudsim/simulations
is not updated yet, so if you know of better source I would change it
thanks
m.
p.s. tested on `5ec41370-cb54-44be-9f00-35031820fc1e` (yesterday I wrongly picked `mars8` which does not exists, triggered manually, so ignore `8215755a-543f-49bc-a81e-46063b992d65`)

SubT submit - add Cave and Tunnel Circuit worlds

---

subt/cloudsim2osgar.py
subt/config/r2.json
subt/docker/robotika/run_solution.bash
subt/marsupial.py
subt/ros/proxy/wait.py
subt/test_marsupial.py
subt/zmq-subt-x4.json

This is experiment with marsupial robots (R2 + SSCI X4 drone) - the first attempt is here `ver92marscp2`, `e70821b7-ca98-4e5c-8248-043a854e843e`.
Beside real `detach` action there is still work to do **when to do it?**
- when the parent (R2) decides
- when the drone decides
- encoded in robot name
At the moment it is stored in `marsupial` config and in robot name. Parent does not have to anything. Last (successful) version was `ver93mars7`

provide first sketch for marsupial robots (R2)

---

osgar/lib/quaternion.py
subt/offseter.py
subt/test_offseter.py

Handle initial non-zero rotation for marsupial robot (the drone has opposite direction, see #729).

Fix localization for marsupial robots

---

subt/breadcrumbs.py
subt/cloudsim2osgar.py
subt/config/r2.json
subt/test_breadcrumbs.py

Explorer R2 config 2 has 12 breadcrumbs. The primary goal was to make marsupial drone working, but the next step is to use the payload.
Reference run is `ver94exbread1tc4`, 5255e55a-121e-4529-939a-3e598823b718.

Fix deployment of breadcrumbs for Explorer R2

---

CHANGELOG.md
setup.py

There was no OSGAR release for almost two years (due to other priorities, mainly SubT). The release was requested by @tajgr half year ago and also I need it for another project as a base.
Note, that I picked ~400 commits to master, which are related to OSGAR (majority is SubT, part is Moon) so I could easily overlook some important bits. I was also thinking if we should keep proprietary robot drivers in "core OSAGAR" but we may review it "later" (already OSGAR v0.2.0 supported external drivers in JSON configuration).
p.s. the tag `v0.3.0` does not exists yet, I would create it after merge into master

Release OSGAR v0.3.0

---

osgar/drivers/logsocket.py

This is WIP (or rather evaluation in progress) and I would like to check how the OSGAR part should look like - there could be configurable parameter if needed, for example. The motivation is device SICK RFU620 (RFID reader) which talks via TCP, but every reading is triggered by empty (!) packet - a bit strange but confirmed via WireShark and SOPAS tool. OSGAR is getting update ~ 2Hz while SOPAS around 20Hz and my guess is that it is related to this TCP_NODELAY ... but usage is in different repository (for now).
Or should be have it set always as it is in this PR?
thanks
m.

osgar/drivers/logsocket.py - set TCP_NODELAY for static IP

---

subt/config/r2.json
subt/multitrace.py
subt/radio.py
subt/test_multitrace.py
subt/zmq-subt-teambase.json
subt/zmq-subt-x2.json
subt/zmq-subt-x4.json

This is the first PR necessary for coordinated exploration/navigation. The position of all robots is shared and broadcasted "on demand". The MTM (Multi Trace Manager) publishes "trace_info", which is just overview of known robots and time intervals. If there are some missing bits then MTM publishes "robot_trace" with positions of all robots. Note, that due to limited packet size (1500bytes) the extra large messages are cut into smaller ones if necessary. See reference run "ver95mtm3ts2" with drone and Teambase (`178838c4-3122-4a16-b71a-1cecbc824927`).
Visibility from Teambase:
`python -m osgar.replay --module app logs\aws\tunnel\TS2\ver95mtm3\T\T400.log --verbose --draw`
and data received on teambase via MTM
`python -m osgar.replay --module mtm logs\aws\tunnel\TS2\ver95mtm3\T\T400.log …

Collect and distribute traces for all robots

---

osgar/lib/quaternion.py
osgar/lib/test_quaternion.py

AssertionError: 1.0000000006479999
return math.acos(2 * inner_product**2 - 1)
ValueError: math domain error
... I wonder if this also happened in the Cave competition. See https://github.com/robotika/subt-artf/issues/116 for reference, B-drone.

osgar/lib/quaternion.py - fix acos overflow

---

subt/cloudsim2osgar.py
subt/main.py
subt/name_decoder.py
subt/ros/robot/launch/freyja.launch
subt/test_name_decoder.py
subt/zmq-subt-x2.json

This is a experiment mentioned in #736. It allows Freyja to log octomap binary data for names with 'XM' extension, i.e. `A600LXM` will explore left side for 600 seconds and store Map. Note, that the map is conditional both in launch file and in `cloudsim2osgar`.

Integrate octomap into OSGAR for Freyja

---

subt/rosbag2log.py

New names are for example:
```
robot_data_affcd00f-3ccf-4ebc-9620-d41635d7044e-r-1_A600L_0.bag
robot_data_affcd00f-3ccf-4ebc-9620-d41635d7044e-r-1_A600L_1.bag
robot_data_affcd00f-3ccf-4ebc-9620-d41635d7044e-r-1_B10W300R_0.bag
robot_data_affcd00f-3ccf-4ebc-9620-d41635d7044e-r-1_C300R_0.bag.active
robot_data_affcd00f-3ccf-4ebc-9620-d41635d7044e-r-1_T600_0.bag
```

Support subt/rosbag2log.py for newly named robot_data_ in ROS bag

---

subt/cloudsim2osgar.py
subt/main.py
subt/points2scan.py
subt/test_points2scan.py

Since release 2021-01-21 the 3D lidar has realistic resolution 1800pts running at 10Hz (instead of 10000 at 15Hz).

Adapt to 3D lidar VLP-16 resolution change

---

subt/main.py
subt/ros/proxy/sendlog.py

SubT changed limit to original 2GB specified in WiKi. According to already recorded files in final qualification world the cut sizes are limited by 1024*1024 * 1000(?) = 1_048_576_000
```
robot_data_9b58abce-64c0-4405-bc27-0e8613bc96df_A600LXM_1.bag	1 048 783 731	04.03.2021 09:03	-a--
robot_data_9b58abce-64c0-4405-bc27-0e8613bc96df_A600LXM_2.bag	913 934 750	04.03.2021 11:01	-a--
robot_data_9b58abce-64c0-4405-bc27-0e8613bc96df_B600RXM_0.bag	1 048 744 643	04.03.2021 09:42	-a--
robot_data_9b58abce-64c0-4405-bc27-0e8613bc96df_B600RXM_1.bag.active	49 672 192	04.03.2021 11:01	-a--
```

Reduce ROS bag limit size to 2GB

---

subt/ros/proxy/sendlog.py

Well, it is running probably in parallel and "does not stop in time" :(
```
robot_data_072efe38-1ac8-42a5-9e96-b923f9b17c9c_B10W1800R_1.bag	1 048 818 864	04.03.2021 19:18	-a--
robot_data_072efe38-1ac8-42a5-9e96-b923f9b17c9c_B10W1800R_2.bag.active	11 859 394	04.03.2021 19:19	-a--
```
so I would drop these extra 2x 48MB :(

Second attempt to fix lost of log files due to 2GB limit overflow

---

subt/script/bridge.bash
subt/script/sim.bash
subt/submission/two-freyjas.toml
subt/tools/run.py
subt/tools/submit.py

I tried to set it up on my new laptop, but I am doing something wrong, i.e. the changes are not properly tested yet :(. There is also change of AWS zone necessary for finals.
```
(osgar) md@md-ThinkPad-P50:~/git/osgar/subt/docker$ python -m subt.tools.submit ../submission/two-freyjas.toml 
world:   Urban Circuit World 1
image:   138467776890.dkr.ecr.us-east-1.amazonaws.com/subt/robotika:ver99rev2
simname: ver99rev2uc1r1
robots:  
A900LXM: ROBOTIKA_FREYJA_SENSOR_CONFIG_2
B900RXM: ROBOTIKA_FREYJA_SENSOR_CONFIG_2
T2000: TEAMBASE
File "/home/md/.virtualenvs/osgar/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
conn = connection.create_connection(
File "/home/md/.virtualenvs/osgar/lib/python3.8/site-packages/urllib3/util/connection.p …
```

Add qualification worlds to run and submit tools

---

subt/main.py
subt/octomap.py

This is follow up of #772 where the image slide is optimized for computation (and not for nicer picture). The box/voxel black borders are removed and now 1024x1024 pixel image covers 512m (still 0.5m resolution).
This is exploration in Finals Qualification for 5 minutes and return home.

Plan safer route in octomap

---

subt/cloudsim2osgar.py
subt/ros/proxy/ros_proxy_node.cc
subt/ros/robot/launch/freyja.launch
subt/ros/robot/launch/k2-virt.launch
subt/zmq-subt-x2.json

This is the first part of refactoring of rosmsg -> cloudsim2osgar. Removed wait for `depth` from rosproxy and relinked configs for Freyja and Kloubak K2 (X2 is no longer supported).

Remove duplicity streams for Freyja and K2

---

subt/image_extractor.py
subt/script/virtual-depth-view.bat
subt/zmq-subt-x2.json
subt/zmq-subt-x4.json

Disable logging of synchronized RGBD data for Freyja, K2 and X4 (R2 is ignored for the moment). There is optional `image_extractor` which saves images and depth with given rate. Depth is by default not logged.

Reduce size of logs with RGBD data

---

subt/artifacts.py
subt/main.py
subt/subt-freyja.json
subt/subt-k2-virt.json
subt/zmq-subt-x2.json

The former version used mixed sources for detector, but due to dropped images there could be "interference" where only front or rear images are missing.

Add 2nd artifact detector for Freyja and K2 robots

---

subt/tf_detector.py

Fixing too benevolent threshold for Rope artefact (causing problems with Finals Qualification world).

Increase score for rope.

---

osgar/lib/pplanner.py
osgar/lib/test_pplanner.py
subt/octomap.py
subt/ros/robot/launch/x4.launch
subt/ros/robot/src/filter_pointcloud.py
subt/test_octomap.py
subt/zmq-subt-x4.json

This is "draft" of current state of Octomap exploration with robots with XM suffix. This version still plans path in single 2D raster, which is cut for Freyja at 0.5m above the ground and for X4 at 2m. The 3D frontiers are "too dense" and they will require another revision never the less there are already useful bits:
* `subt/octomap.py` used as script allow interactive analysis of recorded octomap in 10 levels
* RGBD camera for drone filters out properly propellers (depth is X axis) and inserts out of range rays (10m for RGBD).
* when tested in FP2 it explored parts so far not reachable by left/right wall following (and scored 4 points for X4 + Freyja)
* the map slices are `uint8` grayscale and numpy optimized "drawing"/cutting

Step towards 3D octomap planning

---

subt/cloudsim2osgar.py
subt/main.py
subt/name_decoder.py
subt/octomap.py
subt/ros/robot/launch/x4.launch
subt/ros/robot/src/map_tf_broadcaster.py
subt/zmq-subt-x4.json

This PR is with with small but for next steps important "prelude":
* introduced letter 'E' in name as "exploration" (not to be confused with "explosion") with time, when the robot accepts only external waypoints
* experiments with Open3D for visualization of collected 3D octomap data
* uses `map` frame_id for octomap with small wrapper `map_tf_broadcaster` which handles static TF conversion
OTOH there bits I do not like - one is still duplicate `follow_trace` which is used by robots to enter the gate and by default ignoring Z coordinate (i.e. extra param). The "explore" mode is rather for testing - there is need of cooperation between generation of trajectories and its execution. Also 2m limit is too much. Launch file for Freyja with Octomap was not changed yet.
In general comments if to …

Use global coordinates for X4 octomap

---

subt/tools/submit.py

The Urban Simple worlds were missing in `submit` script, so I added them. First testing run is US2 - `c15a6bb6-51c8-44a0-91a9-e522c2c3ce30` (expected failure due to negative Z for octomap, but it started). Also we have 0 points in all simple worlds ... ;)

subt/tools/submit.py - support also Urban Simple worlds

---

subt/artf_filter.py
subt/artf_gas.py
subt/main.py
subt/test_artf_filter.py
subt/test_artf_gas.py
subt/test_subt.py
subt/zmq-subt-x2.json
subt/zmq-subt-x4.json

This is refactoring of artifact processing in `subt/main.py` to separate module `artf_filter.py`. My main motivation was to run post-processing on already detected artifact and delay the report until verified. And there is also filtering of breadcrumbs as false reports and maybe more :). At the end this is this first step although I will have to review it again in the morning with fresh head.
Note also needed change of gas detector, which is now publishing `localized_artf`. Finally there is no longer "terminated" report of all artifacts after return to home - the robot should broadcast them permanently. If you spot some weakness, please let me know.

Add artifact filter

---

subt/artf_filter.py
subt/test_artf_filter.py
subt/zmq-subt-x2.json
subt/zmq-subt-x4.json

This is the first step to filter 1:1 matching drills and breadcrumbs. There is still danger that Freyja will drop breadcrumb next to the real drill and tolerance 4m could be too long, but due to localization uncertainty the position is sometimes 3m off (to be investigated independently).
(loosing 2 extra artifacts)
Note, that this PR is based on traversibility map branch.

Filter false DRILL detection mismatched with breadcrumbs

---

moon/test_artifacts.py
subt/test_launch.py

These tests are failing for me locally (not representative WinPython 3.6), but after removing them GitHub seems to be happier (last 10(?) build failed on Windows Python 3.8). I would currently disable them.

Remove problematic (failing) tests

---

moon/test_artifacts.py
subt/main.py
subt/octomap.py
subt/script/debug-virtual-view.bat
subt/test_launch.py
subt/zmq-subt-x4.json

This is a small step forward with octomap and exploration:
* interrupt following `waypoints` with new `waypoints`
* visualize Open3D voxel with planned exploration path
* find path every sim 1s and record dropped octomap
* speed-up octomap visualization by skipping intermediate maps
* reduce logging of images for X4 in order to fit 20min into 2GB
* update `debug-virtual-view.bat`

Octomap with 3D planning

---

subt/artf_filter.py
subt/test_artf_filter.py

This is simple artifact filtering. Based on the last Freyja run in FP2 I have seen for properly detected artifacts:
```
0:02:04.584665 ['TYPE_BACKPACK', [12.404765528524946, 7.341454907572785, 0.25001002175853737]]
Confirmed: TYPE_BACKPACK 38
0:06:06.583681 ['TYPE_VENT', [19.190128880089453, -17.86577439674212, 1.9636593698621922]]
Confirmed: TYPE_VENT 12
0:07:14.534541 ['TYPE_CUBE', [20.05912215692238, -34.87304921571129, 0.15473397959270255]]
Confirmed: TYPE_CUBE 25
0:20:40.407697 ['TYPE_PHONE', [-6.7927368090999405, -95.57470150990535, -5.88281186353819]]
Confirmed: TYPE_PHONE 118
...
```
:) so even the phone can be sometimes seen for many frames.
I plan to add now commit increasing the default for `num_confirm` to 1.

Implement confirmation threshold for artifact filtering

---

subt/artf_node.py
subt/test_artf_node.py
subt/tf_detector.py
subt/tools/analyze_detectors.py

This is an attempt to use a more advanced verification of detections. The detections are verified via border between false and true areas. The borders are defined by three points.
The disadvantage is higher amount of detections that needed to be sort out.

Use confidence borders for check detections

---

subt/main.py
subt/rosbag2log.py
subt/tools/ignstate.py

This is rather "misc" branch, where I originally wanted to increase version to `Ver109` to run from master with new thresholds. The result was not good (6 points FQ), so I wanted to check older single Freyja run with 9 points ... but there is slightly different format of `.tar.gz` files with `gazebo` sub-folder. This workaround works for me with outputs:
```
gazebo/subt_finals_2021-05-26T20:44:04.899394422.log
gazebo/events.yml
gazebo/summary.yml
gazebo/score.yml
gazebo/pos-data/A5C2700L-pos.data
gazebo/run.yml
gazebo/state.tlog
gazebo/state.tlog-journal
```
Note, that `A5C2700L-pos.data` is new and we may use it later instead to huge `state.tlog` file (just to validate data received by Teambase, one day).

Parsing new directory structure of SubT Finals logs

---

osgar/tools/log2video.py

Simple extension to convert depth data into heat map (copied from lidarview)
Example of converted dual video: https://youtu.be/YDI4nFPOHHA

log2video.py - support video output also for depth data

---

subt/main.py

just to avoid potential collisions and failure to entry the gate ...
`ver114start` for reference - `54de91c4-cc8e-4c35-ad98-551761776f1c`
Here is an example where it should help (former `ver113`):
and this is result after disable turbo near start:

SubT - no turbo at home

---

subt/tools/draw_pos_data.py

Formerly used "state.tlog" has for FP1 simulation 8GB while sum of these small *-pos.data files
for 8 robots is 815kB. Also the sampling is only XYZ every simulated second, which is enough
for the run overview.
An example FP1:

Draw overview of robot positions from *-pos.data files

---

subt/config/coro_pam.json
subt/image_extractor.py
subt/test_image_extractor.py

This PR should help with logging more interesting images and also to keep the log file size within 2GB limit.
I am not sure about some details:
* external configuration which we do not use now
* parametrize only image with distance and angle (and ignore depth)
* the default 0.1m and 10deg
Reference run `ver116min` `2cfa987d-2c2e-4336-bea7-171d43391b26` - `A600W600L` in TC2

Stop logging while standstill

---

subt/config/coro_pam.json
subt/crash_report.py
subt/test_crash_report.py
subt/zmq-subt-x2.json

Whenever accelerometer value is above the `threshold` new module dumps `crash_rgbd` into log file. The buffer size is limited and on Pam drone it contains all 3 types of RGBD images (left, front, right).
p.s. at the moment I have troubles to crash the drone ;) ...

Generate crash report

---

subt/crash_report.py

This is the first (minimal) step to extract `black_box.crash_rgbd` data and sort it into `fromrospy.{left|front|right}` streams. There is also experimental pose3d lookup but it is available only in `--verbose` mode.
Note, that the crash on stairs we have seen so far is probably caused by drained battery ... so the drone was not able to climb the stairs and return home.
Run:
`python -m subt.crash_report /data/aws/finals/FP2/ver117crash/B600W600RH3600W.log` generates `crash.log` and then
```
(osgar) md@md-ThinkPad-P50:~/git/osgar$ python -m osgar.logger crash.log | grep fromrospy
9                  fromrospy.acc        0 |   0 |   0.0Hz
10             fromrospy.top_scan        0 |   0 |   0.0Hz
11          fromrospy.bottom_scan        0 |   0 |   0.0Hz
12               fromrospy.pose3d …
```

Convert crash report

---

.dockerignore

`subt/submission` folder contains some configurations tracked in git + in my case also many local copies and experiments used for CloudSim. When the simulation is used locally it stores logs next to the original `*.toml` file, i.e. in my case `subt/submission` which is then becoming part of next docker image ...

Docker ignore subt/submission folder with configs and logs

---

subt/crash_report.py
subt/zmq-subt-x2.json

In FP2 the log was mostly filled by passing door steps, which were not real crash. There were even values acc = 142, which was still
not collision. 100 seems to be reasonable limit until true crashes appear.
Old values (FP2, 5 points, `d9f13a84-d472-4529-95fd-744e493e72a0`)
```
acc trigger: 89.39034034719842 (buf size = 100)
acc trigger: 65.35707224576463 (buf size = 19)
acc trigger: 36.41460221570327 (buf size = 69)
acc trigger: 31.28264106868771 (buf size = 39)
acc trigger: 35.44149196435406 (buf size = 100)
acc trigger: 31.983370287642508 (buf size = 100)
acc trigger: 30.153607507330968 (buf size = 100)
acc trigger: 30.487644161911 (buf size = 100)
acc trigger: 76.04633363357651 (buf size = 100)
acc trigger: 92.14781603192566 (buf size = 100)
acc trigger: 33.18709088996603 (buf size = …
```

Increase Freyja acc crash threshold from 30 to 100

---

subt/artf_gas.py
subt/config/coro_pam.json
subt/test_artf_gas.py

Reference run UP1 (`dcb87ea7-af18-4159-9f9f-4f25c60eef68`) ... not sure where is the closest gas :( ... and FPR1 is not available yet.

Fix Gas detection for drones - move Z coordinate to the ground

---

subt/artf_filter.py
subt/artf_reporter.py
subt/radio.py
subt/test_artf_reporter.py

This is attempt to reduce reports from multiple robots when the base station is not available and thus the hypothesis cannot be directly evaluated. In particular please have a look at unittest and optionally suggest more cases. For example note, that nearby artifact will not be reported again if it was already classified as false (so localization errors could be fatal). Thanks in advance for comments.

Reduce multiple reports

---

subt/tools/run.py
subt/tools/submit.py

WIP - waiting for fix on CloudSim side, see osrf/subt issue 1000 from Meryl
```
{
"errcode": 3013,
"msg": "Invalid value in field.",
"extra": [
"Circuit:Finals Preliminary Round World 1"
],
"errid": "5c17e6ad-113e-47c5-81a3-2800b1125ed9",
"route": "POST /1.0/simulations",
"user-agent": "",
"remote-address": "109.164.32.171"
}
```
@jisa I suppose that you would like to have it also for local run, but for that I need to update my sim images to test it

Add fprX (finals preliminary round worlds) to submit tool

---

subt/main.py

just that we do not have to comment and uncomment imports

Add option --use-old-record for legacy System code in subt/main.py

---

osgar/drivers/imu.py
osgar/drivers/test_imu.py

In original the "orientation" stream contained all data provided by IMU. Now, this stream is renamed to "data" and "orientation" contains quaternion.

imu.py: publish quaternion through "orientation"

---

osgar/drivers/replay.py

This PR fixes streams registration and  adds a sleep option to slow down recording.
I used it during testing of node for lidar processing. This tool may partially replace a real sensor if needed.

Dummy record via drivers/replay

---

examples/gym/gym_simulator.py
examples/gym/test-gym_simulation.json

This PR enables use steering angle beside angular speed in the Gym simulator. The simulator robot uses Ackerman steering. The name of the channel is "move" as well as for Spider.

steering angle in gym simulator

---

config/test-vanjee-lidar.json
osgar/drivers/__init__.py
osgar/drivers/test_vanjee.py
osgar/drivers/vanjee.py

This is the first attempt for VanJee 4-lines lidar integration. I expect changes (mainly test) once integrated on robot and used. In particular while scan for horizontal line is compatible with former SICK scan there is nothing similar for additional 3 layers. XYZ pointcloud from Velodyne is on the other hand overkill, I think. So for now "something in between". More info available on
https://robotika.cz/articles/vanjee-lidar/

Add driver for VanJee Lidar

---

config/eduro-go.json
osgar/lib/config.py
osgar/lib/test_config.py
osgar/record.py

The variable application for config file is deprecated so there is a need to pass variable configuration parameters via `osgar.record`. This PR provides new way using `--param key=value` for example `--param app.max_speed=0.1`. This was experimentally tested on robot Eduro.

Add optional configuration parameters for osgar.record

---

osgar/lib/icp.py
osgar/lib/test_icp.py

This is a slightly improved version of ICP, verified matrix computations and yes, the next step is to drop outliers. Follow me breaks matching ("as expected), as well as not matching parts of environment.

ICP - slightly faster, unified matrix calculations

---

config/test-dual-timer.json
osgar/lib/config.py
osgar/lib/test_config.py
osgar/record.py

I would like to minimize the number of needed configuration JSON files. This is proposal for `--without` option to `osgar.record` which removes given module (or list of modules) from config and all its dependent links. Inspiration is from `poetry.lock`:
https://python-poetry.org/docs/cli/#install
where the original `poetry.lock` is already consistent with versions, but you may want to install only some packages. Later we may add also `--with` and "optional modules" ... but "later may never come".
Example:
```
(osgar) md@md-ThinkPad-P50:~/git/osgar$ python -m osgar.record --duration 10 config/test-dual-timer.json
2024-01-14 21:55:06,225 root             WARNING  Environment variable OSGAR_LOGS is not set - using working directory
2024-01-14 21:55:06,226 __main__         INFO …
```

add to ogar.record option --without (list of modules)

---

osgar/drivers/replay.py
osgar/lib/config.py
osgar/record.py

It allow add channels with ":" in configs for replay driver. E.g.: 
```
"driver": "replay",
"init": {
"filename": null,
"pins":{
"oak_d.depth": "depth:null"
}
```
Moreover, there is improved `--parrams` flag from `osgar.record`. It is easier to set string value now. E.g.:
`--params app.filename=data/logy_23/some.log`

driver.replay - register channels

---

config/eduro-followpath.json
osgar/followpath.py
osgar/test_followpath.py

This is simple follow path tested on Eduro. Can be used with external parameters like
`python -m osgar.record --params app.max_speed=0.2 app.path="[[0,0], [1,0], [1,0.5], [0,0.5]]"`
or looping
`python -m osgar.record --params app.max_speed=0.2 app.path="[0,0], [1,0], [1,0.5], [0,0.5], [0, 0], [0.1, 0]]"`
There is expected to be further development - FR07 support, variable speed, angle correction, accept new path as message, ...

Add followpath node

---

osgar/drivers/pcan.py

Python CAN has by default (to my surprise) log level "debug" (!), which is basically impossible to use once the communication is running (the CAN messages are printed). This one-liner allows change in config + sets as default "info".
For more info see:
https://python-can.readthedocs.io/en/v4.3.1/internal-api.html#can.util.set_logging_level
can.util.set_logging_level(level_name)[[source]](https://python-can.readthedocs.io/en/v4.3.1/_modules/can/util.html#set_logging_level)
Set the logging level for the “can” logger.
Parameters:
level_name ([str](https://docs.python.org/3/library/stdtypes.html#str)) – One of: ‘critical’, ‘error’, ‘warning’, ‘info’, ‘debug’, ‘subdebug’, or the value [None](https://docs.python.org/3/library/constants.html#None) (=default). Defaults to ‘debug’.
Return type: …

osgar/drivers/pcan.py - change log level from debug to info

---

osgar/tools/lidarview.py

The lidarview does not work if only pose3d is available. It looks there is just wrong indentation. However, i am not sure so please for careful review.

Bugfix - lidarview pose3d

---

osgar/platforms/yuhesen.py

This is just SW "safety fuse" for "wild" (or obsolete) control programs like `followme.py`, which is not handling `max_speed`. In short to avoid situations like: https://robotika.cz/robots/pat-a-mat/cs#240407

Add SW limit max speed and steering angle for FR-07 platform

---

osgar/logger.py
osgar/replay.py

Add new option `--duration` (similar one is used in `record.py`) to limit how long log file is used for replay. Useful for quick check and/or in combination with `--draw` feature.
Also handle corrupted log files (zeros at the end) and report it.

Extend replay.py by --duration and handle corrupted end of log files

---

config/test-oak-camera-usb.json
osgar/drivers/oak_camera.py

* extend video encoders
* gzip depth data
before:
```
(osgar) md@md-ThinkPad-P50:~/git/osgar$ python -m osgar.logger /home/md/git/osgar/test-oak-camera-usb-240507_171842.log
k                 name    bytes | count | freq Hz
--------------------------------------------------
0                  sys     1243 |  9 |   0.9Hz
1            oak.depth 35337246 | 69 |   6.9Hz
2            oak.color 32602560 | 68 |   6.8Hz
3 oak.orientation_list    36366 | 66 |   6.6Hz
4       oak.detections        0 |  0 |   0.0Hz
5        oak.depth_seq      759 | 69 |   6.9Hz
6        oak.color_seq      748 | 68 |   6.8Hz
7   oak.detections_seq        0 |  0 |   0.0Hz
Total time 0:00:10.039510
```
after
```
(osgar) md@md-ThinkPad-P50:~/git/osgar$ python -m osgar.logger …
```

OAK-D support H264 and H265 video encoding and gzip detph data

---

osgar/drivers/gps.py

I found, that the gps module crashes due to attempt to publish this stream. It is related to u-blox GPS. See in `parse_bin`.

gps.py: register also rel_position

---

osgar/tools/lidarview.py

This is a hacky way of support of H264 encoding (maybe also H265, not sure) for LidarView. Note, that I still do not know better way how to convince OpenCV to read from stream, unless we would like to merge some other 3rd party library??
Also note, that this hack works only for forward motion (OAK-D has default 1 key frame and 9 update frames).

LidarView - support for H264 video stream

---

osgar/logger.py

Add the same `--duration` option also to `osgar.logger` (next to `osgar.record` and `osgar.replay`). The code was already there (needed for replay), so now it is just public. Motivation is creation H264 video for YouTube from OAK-D camera where interesting is only the first part. An example:
```
python -m osgar.logger /data/pat/2024_05_18/pat-go-314-240518_082742.log --stream oak.color --raw --duration 300 > roro24-pat-1st-round.h264
```
was used to generate https://youtu.be/UKBNOBJEYZU

Add option --duration also to base logger

---

osgar/drivers/gps.py
osgar/drivers/test_gps.py

This PR is a partial refactoring of the gps driver.
The driver is now publishing `nmea_data` stream in addition to `position` and `rel_position`. The driver first gets  data from nmea sentence and then calculate old position in ms.
There is also corresponding modification of gps unit tests.
The code is tested on two logs with different gps receivers for now. In this moment I would like to continue in testing because the reliability of this driver is very important.

gps: publish nmea message

---

osgar/replay.py

Fixing #1002 `TypeError: LogReader.__init__() got an unexpected keyword argument 'duration'`

osgar/replay.py - fixup duration

---

osgar/go.py
osgar/test_go.py

It is useful to test not only straight motion there and back, but maybe also turn. More over we have some robots which have steering (Pat, Spider, Matty, John Deere) and other (Eduro, Freya) have differential drive. By default Go will publish both `desired_speed` and `desired_steering` with 0. If you specify angle for steering or angular speed, then only one interface is used.

Extend Go by option to specify steering angle or angular speed

---

osgar/bus.py

This is the old painful replay, which looked like some error:
```
File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/home/md/git/osgar/osgar/node.py", line 44, in run
self.update()
File "/home/md/git/osgar/osgar/node.py", line 32, in update
timestamp, channel, data = self.bus.listen()
File "/home/md/git/osgar/osgar/bus.py", line 167, in listen
dt, stream_id, bytes_data = next(self.reader)
File "/home/md/git/osgar/osgar/logger.py", line 252, in __next__
return next(self.gen)
StopIteration
```
With SystemExit() [thanks Jirka!] it terminates nicely without exception ...

Handle properly replay termination at the end of logfile

---

osgar/platforms/matty.py
osgar/platforms/test_matty.py

Yeah, I should divide the steering angle by 2 ...
... because for 90 deg (not feasible for the robot) it would be radius = 1/2 of the body length (axis to center joint).
The odometry was recalculated with this fix and the result is in #1010 description.

Fix platform Matty odometry calculation

---

osgar/tools/lidarview.py

When the d-key is pressed, the program crashes because `np.savez_compressed` tries to store pose3d as an np.array. A possible solution is to split pose3d into xyz and qvat.

lidarview: fix export bundle data

---

osgar/platforms/matty.py
osgar/platforms/test_matty.py

The ESP32 actually publishes status including if Emergency STOP button is pressed but this info was not forwarded in OSGAR. This one if "must have" for automatic starting of logging and termination on stop button change (terged RORO25).

Platform Matty - fix publishing emergency_stop

---

osgar/tools/lidarview.py

In particular it extends existing detection of I and P frames from H.264 also to H.265 prefixes

Support H.265 in osgar.tools.lidarview

---

osgar/lib/depth.py
osgar/lib/test_depth.py

It is way how to align depth to color image in post-processing. Currently tested on oak-d-pro-poe camera. The function only recalculates the depth and does not perform interpolation. So if the color image has a higher resolution, it will contain many zero pixels

depth to rgb align

---

osgar/drivers/oak_camera.py

In particular use LEFT mono camera for object detection. Note, that in the night is oak.color basically unusable and IR is visible only in stereo pair left and right cameras. This code was tested with https://github.com/robotika/osgar-apps/blob/feature/geofence/dtc-systems/config/oak-camera-night.json config.

OAK driver - add support for NN processing on night vision

---

osgar/tools/get_module_io.py

This is a simple (i.e. not perfect) tool for listing OSGAR module inputs and outputs:
```
(osgar) md@md-ThinkPad-P50:~/git/osgar-apps/dtc-systems$ python -m osgar.tools.get_module_io doctor:Doctor
doctor:Doctor (['audio', 'h265_video', 'report_latlon', 'scanning_person'], ['report'])
(osgar) md@md-ThinkPad-P50:~/git/osgar-apps/dtc-systems$ python -m osgar.tools.get_module_io osgar.drivers.lora:LoRa
osgar.drivers.lora:LoRa (['artf', 'cmd', 'pose2d', 'pose3d', 'radio', 'raw'], ['raw'])
```

Add tool for listing inputs and outputs of OSGAR module

---

osgar/logger.py
osgar/record.py

This bug made me crazy for "years" :( ... if you kill some recording with Ctrl+C where there are not many data typically everything was lost (only 16 bytes header was available). This solves the problem (tested with LoRa base-station logger).

Flush properly log file on Ctrl+C termination

---

osgar/record.py
osgar/replay.py
osgar/test_record.py

The motivation is 5 robots which should behave differently in particular situations. There is already `OSGAR_LOGS_PREFIX` to distinguish origin of the logfile, so this is step further, that the robots can use this info and behave differently base on this info. OTOH we still want to keep the replay capability and this saving this environment info into config.
Example of new config (automatically filled):
```
0:00:00.000459 0 b"{'version': 2, 'robot': {'env': {'OSGAR_LOGS_PREFIX': 'm05-'}, 'modules': {'app': {'driver': 'dtc:DARPATriageChallenge', 'in': ['emergency_stop', 'pose2d',
```

Support environment variables in config
