robotika/osgar

lib/camera_marks.py

The function "marksDetektor" takes an image and returns a list of "red stains".
No integrated in the main code.

Landmarks detection via camera. ver 0.

---

conda-linux.yml
conda-win32.yml

I've started with conda environment file:
```yml
name: osgar
channels:
- conda-forge
- defaults
dependencies:
- certifi=2017.4.17=py27_0
- jpeg=9b=vc9_0
- libpng=1.6.28=vc9_0
- libtiff=4.0.6=vc9_7
- opencv=2.4.13=np113py27_1
- pip=9.0.1=py27_0
- python=2.7.13=1
- setuptools=33.1.1=py27_0
- vc=9=0
- wheel=0.29.0=py27_0
- wincertstore=0.2=py27_0
- zlib=1.2.11=vc9_0
- mkl=2017.0.1=0
- numpy=1.13.0=py27_0
- vs2008_runtime=9.00.30729.5054=0
```
but I am to entirely happy with the result. From the package names it is clear there are platform specific packages so this would be the win32 version of the environment.
But I guess this is as good as it gets (?)
Recreate on Windows 7 with
```
$ conda env create -f conda-win32.yml -n osgar
```
@m3d Let me know if it works for you.
Further work:

Conda environment file.

---

apyros/metalog.py
apyros/test_data/meta_160628_174658.log
apyros/test_data/meta_170516_192926.log
apyros/test_metalog.py
helper.py

This is cherry-picked commit with extra code in metalog for support of missing records.

Handle remission as optional logged source.

---

tools/logparser2.py

I think this represents fairly sane API for reading logs.

Refactor common code for zip and dir based logs.

---

tools/logparser2.py

To be rebased on top of #29 once it is merged.
@m3d Feel free to pre-review.

Replace inplace sort with lazy mergesort.

---

tools/logparser2.py

To be rebased on top of #30.
@m3d Feel free to pre-review.

Return jpg data instead of filename.

---

navpat.py

This is the first of 3 planned PR based on feature/test171010. The purpose is to detect laser failure and in that case stop immediately (raise NoLaserData exception).

Stop navpat.py in case of 1s laser failure

---

config/test-gps-imu.json
drivers/__init__.py
drivers/gps.py
drivers/imu.py
drivers/test_gps.py
drivers/test_imu.py
lib/logger.py
robot.py

This is second implementation of driver - IMU (Inertial Measurement Unit). The IMU parser was already part of some older PR, but it was split. Now there is code for reading COM port (mostly copy & paste from `drivers/gps.py`, unfortunately). There is overlap in `serial.Serial` and also parsing NMEA. On the other hand in both cases we may soon switch to binary protocols.

Integrate IMU driver

---

doc/sphinx/logging.rst

I was thinking that we could add motivation section why do we care so much about logs. This piece of text is from never published TDDFR article (Test Driven Development of Field Robots) we sketched with Joris back in 2015.

Add logging.rst with motivation section

---

drivers/bus.py
drivers/gps.py
drivers/logserial.py
drivers/test_bus.py
drivers/test_gps.py
lib/logger.py

This is the first step to creation of `LogSerial` described in in https://github.com/robotika/osgar/pull/44#issuecomment-364014286
I am not sure if to modify `drivers\gps.py` as the first example or in separate PR? The same holds for replay and handling `process` and communication queues.

Create wrapper and logger for Serial com

---

config/test-spider.json
doc/sphinx/can.rst
drivers/__init__.py
drivers/logserial.py
drivers/spider.py
drivers/test_logserial.py
drivers/test_spider.py

This PR is planned to be merged after merge of #43 
You can have a look at the last commit only "Integrate driver.spider" (and potential fixups). This code parses CAN messages and handles basic functionality to communicate with Spider over CAN bus bridge.

Driver for Spider

---

ro2018.py

This is a sketch of replay log files for single module (RoboOrienteering2018) as shortly discussed over email. The question is where to move `LogBusHandler`, how to handle IDs with names and deserialization?

ro2018.py - handle replay log

---

osgar/drivers/logsocket.py
osgar/drivers/test_logsocket.py

At the moment it is only logging of TCP communication (it used to be part of `apyros`).

Implement LogTCP for SICK laser integration

---

osgar/replay.py

A small bug discovered "on the way"

replay.py - fix missing import

---

osgar/drivers/gps.py

This was part of porting OSGAR to RaspberryPi with Marina boat. There was no need for numpy (see cherry-picked commit). Now I checked that also the main script section is obsolete (record worked but replay did not). The same functionality can be obtained via
`python osgar\robot.py run config\test-windows-gps.json`
and
`python osgar\replay.py robot-test-180910_043732.log --module gps`

Remove dependency of gps.py on numpy

---

osgar/logger.py
osgar/test_logger.py

Workaround for large data blocks (the first option as discussed in #84 ).

logger.py - support large data blocks

---

setup.py

ready for release ... maybe. Should we add supported low lever protocols, sensors and robots? Should be released after README.md update (#88).

Add setup.py for OSGAR library with dependencies

---

README.md

Update README.md 
Cherry-picked commits from "feature/eduro" branch.

README.md - update info about new OSGAR interface

---

config/eduro.json
doc/sphinx/eduro.rst
doc/sphinx/index.rst
osgar/drivers/__init__.py
osgar/drivers/eduro.py
osgar/drivers/test_eduro.py

Cherry-picked commits from `feature/eduro` +add unittest. (I will rebase it after merging other PRs)

Add Eduro robot

---

README.md

Update README.md with usage of record.py

---

osgar/followme.py
osgar/go1m.py
osgar/launcher.py

This is a refactoring of argument parsing for OSGAR applications. Two examples (FollowMe and GoOneMeter) were used but when accepted also examples and explore from #120 will be refactored.

Introduce application launcher and refactor FollowMe and GoOneMeter

---

config/test-opencv-camera.json
osgar/drivers/opencv.py

This is primarily driver for camera Robik.
Note, that I did not add it into "all_drivers" because of dependency on OpenCV.

Add OpenCV driver for camera logging

---

osgar/tools/lidarview.py

- filter out too many points based on grid histogram
... simple drawing "map" based on accumulated points restricted to 0.5m x 0.5m grid (oldest is kept)

lidarview - draw accumulated points

---

osgar/drivers/logsocket.py
osgar/drivers/test_logsocket.py

sleep was in config but code did not process it

LogHTTP - bugfix accept sleep parameter

---

osgar/logger.py

List of streams, name, size, message count per channel, frequency and
total time.
```
M:\git\osgar>python -m osgar.logger --stat robik-wall-190228_131730.log
0                        sys       1737 |    10 |   0.0Hz
1                 camera.raw  207141835 |  4343 |  14.7Hz
2 cortexpilot.emergency_stop          0 |     0 |   0.0Hz
3           cortexpilot.scan   12489426 | 27173 |  92.2Hz
4       cortexpilot.encoders      84456 | 27953 |  94.9Hz
5         cortexpilot.pose2d     263086 | 27953 |  94.9Hz
6            cortexpilot.raw     559108 | 27956 |  94.9Hz
7                 serial.raw   15710190 | 27964 |  94.9Hz
8          app.desired_speed     261374 | 27168 |  92.2Hz
```

logger.py - add option --stat for statistics

---

osgar/explore.py
osgar/test_explore.py

This is the explore.py used for tests in Štola Josef on both robots (cortexpilot and eduro).

Cherrypick explore.py from eduro-subt branch.

---

osgar/logger.py
osgar/test_logger.py

First shot at log reader with random access. 
Known issues:
Motivation: It should allow creating UI to jump to any place in the log or go back in time without limits. For STIX we could have an analysis that would identify "interesting" places/times in the log that we could directly jump to, to verify whatever there is.

RFM: LogIndexedReader

---

osgar/logger.py
osgar/test_logger.py

Fix reading partial log files.

---

osgar/bus.py
osgar/replay.py

At `publish` time the `listen` queue is checked and the oldest timestamp
in the queue is compared with the `publish` timestamp. This difference
is tracked as `max_delay`. If this delay is larger then
ASSERT_QUEUE_DELAY (currently 0.1s), then warning is output to stdout.
I was using this code to check if everything is on time in the SubT Virtual Track.

During replay track and report how fast a module reacts.

---

osgar/tools/lidarview.py

This further builds up on LogIndexedReader #150 (so to ease review the PR is temporarily against the feature/logger2 branch).
The integration is somewhat minimal so far. If we can agree this is the way to go, we may prune some of the code in lidarview.
The visible feature being added is limitless history and without caching.

Add Framer (LogIndexedReader based) to lidarview.

---

osgar/drivers/__init__.py
osgar/lib/config.py

I am converting `all_drivers` variable into a name:entry_point map. I went for minimal invasiveness.

Lazyload drivers

---

config/test-usb-camera.json
osgar/drivers/__init__.py
osgar/drivers/usbcam.py

Needs stuff from https://github.com/zwn/libuvc and https://github.com/zwn/pyuvc already installed.
To see all supported cameras currently attached, run
```
python -c "import uvc; from pprint import pprint; pprint(uvc.device_list())"
```
I get on my system:
```
[{'bus_number': 1,
'bus_ports': [5],
'device_address': 2,
'idProduct': 22049,
'idVendor': 3034,
'manufacturer': 'KS0HD05012839056B6LM03',
'name': 'HD WebCam',
'serialNumber': '200901010001',
'uid': '1:2'},
{'bus_number': 1,
'bus_ports': [3],
'device_address': 5,
'idProduct': 5461,
'idVendor': 5546,
'manufacturer': 'RYS HFR USB2.0 Camera',
'name': 'RYS HFR USB2.0 Camera',
'serialNumber': 'unknown',
'uid': '1:5'}]
```

First shot on libuvc supported cameras.

---

osgar/tools/calibfish.py

Add tool to calibrate fisheye camera.

---

config/kloubak-slot.json
config/kloubak-subt-camera.json
config/kloubak-subt.json
osgar/drivers/sicklidar.py
osgar/replay.py

These are some tweaks from feature/kloubak branch to properly support 100Hz motors, TIM881 and nicer replay in case of missing connections.
PR for kloubak inself will be separate PR

minor tweaks

---

setup.py
subt/__main__.py
subt/main.py

To test run `pip install -e .`. Afterward you can run `subt` or `python -m subt` from any directory and it will do the right thing.

Add `subt` tool, support `python -m subt`.

---

osgar/tools/lidarview.py

See https://stackoverflow.com/a/55769463/3185929.

Hide pygame support prompt.

---

config/eduro-subt-estop.json
config/eduro-subt.json
config/subt-e-stop-windows-A24.json
osgar/lib/test_virtual_bumper.py
osgar/lib/virtual_bumper.py
subt/main.py

Fix E-stop, implement virtual bumper and support non-symmetric robots

---

subt/report_artf.py

This is version without authorization token.

report_artf.py - update comments and add extra sleep

---

subt/main.py

there could be also problems on the return back to home, so it has sense to have safety limits there too

subt/main.py - add safety limits also for return home

---

osgar/tools/lidarview.py

simplify manual reporting of artifacts position

lidarview.py - add helper for rotation computation

---

subt/main.py

I have moved parts of update() into its own methods to make the update() method shorter and easier to grok.

subt/main.py: refactor update()

---

osgar/lib/test_virtual_bumper.py
osgar/lib/virtual_bumper.py
subt/main.py

This is mix of two PR, as bug in Virtual bumper was discovered during testing of LoRa Pause. There is also refactoring of "collision" interpretation - the robot has to leave given radius within given time limit.

LoRa SubT Pause/Continue and bug fix virtual bumper

---

osgar/tools/lidarview.py

For easier artifact report
The output for print position then looks like
```
(9.835, -0.332, 0.09826203688728075)
rotation (deg) = -1.9333989070929987 dist = 9.840602064914526
```

lidarview.py - print distance from the start

---

examples/sick2018/sick2018.py
osgar/drivers/logserial.py
osgar/drivers/logsocket.py
osgar/go.py
osgar/record.py
osgar/ro2018.py
osgar/turn.py
subt/main.py

This is a part of feature/writer branch. Integrating it into the master should have no downsides while it allows us to keep the changes outside of master smaller and easier to experiment with.

Convert all usages of LogWriter to context manager.

---

config/kloubak2-subt-estop-lora.json
osgar/drivers/kloubak.py
osgar/drivers/test_kloubak.py
osgar/turn.py
subt/main.py
subt/script/run_kloubak2.sh

This is the "raw" code used the very last day for SubT Challenge on robot Kloubak K2. I would probably squash it (at least some parts), but in general I would like to keep it in master. There are some bit I would review (limits for turn in radians instead of degrees), but I would do it as second step. On master I would tag it (?).
There is also fix for `turn.py` utility.

Feature/kloubak2 SubT final code

---

osgar/tools/log2video.py

This is extension of `log2video` tool to generate combined video of two cameras (for SubT it was case of Robik and Kloubak).

log2video.py - add --camera2 option for dual camera setup

---

osgar/record.py

This is an old old thing. It needs to be tested on real hw - I have done only limited testing locally.

Remove (hidden) requirement to have self.bus attribute.

---

osgar/record.py

Following on https://github.com/robotika/osgar/issues/115#issuecomment-535525583 this adds SIGINT handler that calls `request_stop` on all running modules instead of just raising `KeyboardInterrupt` exception in the main thread.
This should move us a little step closer to being able to log and replay shutdown.

Handle SIGINT gracefully.

---

.travis.yml
osgar/bus.py
osgar/test_bus.py
setup.py

In addition to updating `setup.py`, I have also updated travis to test on all python versions we are interested in.

Raise minimum python version to 3.6.

---

subt/docker/robotika/CMakeLists.txt
subt/docker/robotika/Dockerfile
subt/docker/robotika/ros_proxy_node.cc
subt/docker/robotika/run_solution.bash
subt/docker/sln_bash/Dockerfile

2nd PR regarding move `feature/virtual-ignition` to master ...
this is C++ code sending data to Python3 via ZeroMQ
"sln_bash" docker is used for easier development while "robotika" is used for final deployment
The code is based on "subt seed example" and "CMakeList" is modified because of ZeroMQ install

Dockerfiles and C++ code for "robotika" and debugging "sln_bash"

---

osgar/drivers/kloubak.py
osgar/drivers/test_kloubak.py

kloubak.py - encoder calibration for large winter wheels

---

examples/sick2018/sick2018.py
osgar/drivers/rosmsg.py
osgar/drivers/test_cortexpilot.py
osgar/drivers/test_eduro.py
osgar/drivers/test_logsocket.py
osgar/drivers/test_logzeromq.py
osgar/go.py
osgar/launcher.py
osgar/record.py
osgar/ro2018.py
osgar/test_record.py
osgar/turn.py
subt/aws2info.py
subt/main.py
subt/rosbag2log.py
subt/test_artifacts.py

This one is based on #259 and should go in after. 
It brings us one step closer to unified launching.

Further refactor record

---

config/kloubak3-subt.json

This is preliminary configuration for robot Kloubak K3 with a single
SICK lidar, OpenCV camera, E-stop and LoRa. It is designed primarily for
SubT Challenge. There is no artifact detection and IMU was not mounted
yet.

Add config/kloubak3-subt.json

---

examples/myrobot/myapp.py
examples/myrobot/myrobot.py
osgar/bus.py
osgar/drivers/fusion.py
osgar/drivers/kloubak.py
osgar/drivers/logserial.py
osgar/drivers/logsocket.py
osgar/drivers/vesc.py
osgar/explore.py
osgar/followme.py
osgar/go.py
osgar/gpsnav.py
osgar/test_followme.py
osgar/test_node.py
osgar/turn.py
subt/artifacts.py
subt/estop.py
subt/wifisignal.py

I still might have missed something. It is not that easy to find all of them.

Add bus.register calls.

---

osgar/drivers/lora.py
osgar/drivers/test_lora.py
subt/control_center_qt.py

As discussed I've squashed all qt-related commits and set up this PR. This "version 0" should be enough to do some real world testing.

control center

---

subt/doc/virtual-howto.md

This is basic info how to start docker `unittest` and also solution for development

Add basic information how to run robotika SubT Virtual dockers

---

osgar/bus.py
osgar/logger.py
osgar/replay.py

I am not very proud of it, but it works. Later a better refactoring will be needed.

Quick replay bugfix - respect outputs bus.register().

---

osgar/drivers/__init__.py
osgar/drivers/timer.py
subt/control_center_qt.py

As agreed we will make a time based pseudo-release to be ready for testing either on Tuesday or Friday. So this one is aimed at Tuesday December 17th 2019.

Control Center v1

---

subt/artifacts.py

subt/artifacts.py - fix detection debug tool

---

subt/rosbag2log.py

- dump also rosout.log
- add option --all to extract both robot_data ros bags
- use --all option also for SQLite record (common for all robots)

subt/rosbag2log.py - extract also other file

---

subt/ign_poses.py

- fix variable ID for dynamic objects
- complete parsing pose3d for all robots (as generator)
- draw images and handle clipped database
- allow filtering by robot name --only-robot

Add subt/ign_poses.py for decoding simulation state.tlog

---

osgar/drivers/cortexpilot.py
osgar/drivers/realsense.py
osgar/drivers/test_realsense.py
osgar/lib/quaternion.py
osgar/lib/test_quaternion.py
subt/main.py

lib/quaternion.py - change (w, x, y, z) to (x, y, z, w)

---

osgar/drivers/realsense.py
osgar/drivers/test_realsense.py

There are 2 commits:
- general refactoring without other changes
- addition of pose3d output to realsense driver compatible with subt/main.py:pose3d output

Add pose3d output to realsense driver

---

osgar/bus.py
osgar/explore.py
osgar/lib/depth.py
osgar/lib/test_depth.py
osgar/test_explore.py
subt/artifacts.py
subt/depth2scan.py
subt/docker/robotika/run_solution.bash
subt/local_planner.py
subt/main.py
subt/script/debug-virtual-view.bat
subt/script/virtual-depth-view.bat
subt/script/virtual-view.bat
subt/test_artifacts.py
subt/test_depth2scan.py
subt/test_local_planner.py
subt/zmq-subt-x2.json

This is original last development branch for SubT Virtual Urban Circuit. I plan few more rebases in order to reduce numbes of commits

Feature/reduce false artifacts & Urban Circuit release

---

osgar/drivers/kloubak.py

Encoders from passive axle, fixup on K3

Driver kloubak: encoders from passive axle, fixup on K3

---

subt/script/debug-virtual-view.bat
subt/script/eduro-view.bat
subt/script/kloubak-view.bat
subt/script/robik-view.bat
subt/script/virtual-depth-view.bat
subt/script/virtual-view.bat

The same as helpers for SubT Virtual. For example if you want to use tracking camera instead of default
you run:
`subt\script\kloubak-view.bat mydata.log --pose2d rs.pose2d`

extend viewer bat files for optional parameters

---

subt/control_center_qt.py

This is just a quick workaround that the grid is not too dense ... but it should be sufficient for SubT Urban Circuit ...

subt/control_center_qt.py - variable grid size (1, 5, 10, 20, 50)

---

subt/main.py

subt/main.py - fix LoRa STOP to be always available

---

config/test-winsen-gas-detector.json
osgar/drivers/test_winsen_gas_detector.py
osgar/drivers/winsen_gas_detector.py

- add config/test-winson-gas-detector.json

add winsen_gas_detector.py with config

---

subt/control_center_qt.py

On laptop keyboard is '+' with Shift, which makes it harder to control.

subt/control_center_qt.py - accept '=' as ZoomIn

---

osgar/bus.py
osgar/test_bus.py

When shutdown is initiated during the time when a module is sleeping, it was ignored.

bus: make sleep interruptible

---

subt/main.py

This is replacement of `go_straight(2.5)` which was used to enter the tunnel. Different direction from IMU or RealSense is not handled yet.
There is also plan to introduce `--init-path`, which would hold say L-shaped start

subt/main.py - introduce --init-offset

---

subt/script/run_kloubak2.sh
subt/script/run_kloubak3.sh

run scripts for K2 (left, speed 0.7, timeout 1200) and K3 (left, speed 0.7, timeout 300),

subt/script/run: run script for K2 and K3

---

subt/check_gas.py

Simple utility for tomorrow to detect highest concentration of gas (similar to `check_phone.py`

Add subt/check_gas.py utility

---

subt/scan_mixer.py
subt/test_scan_mixer.py

@m3d I have squashed all my commits into one. I am not sure how you want yours. Can you take a look?

Add scan mixer

---

subt/main.py

This reverts commit d74f2ed8b29b8911c518f38a8d6c19a1d42b14ba.
During testing we have found some problems.

Revert "go safety using safety from local planner"

---

subt/main.py

reduce default dangerous dist to 0.3

subt/main: reduce default dangerous dist

---

.travis.yml
osgar/__init__.py
osgar/drivers/__init__.py
osgar/lib/__init__.py
subt/__init__.py
test.py

We are not running tests often enough locally. For me one inconvenience has been the lack of an easy way to do so.

test.py: run all test in the repository

---

subt/script/sync.sh

It is said that it should be faster like this :wink:

Do release build of ros_proxy_node.

---

subt/docker/robotika/ros_proxy_node.cc
subt/docker/robotika/run_solution.bash

I've taken inspiration in `feature/virtual-drone` branch wrt robot name handling and hopefully made it simpler and more straight forward.

Refactor virtual robot_name handling.

---

subt/docker/robotika/ros_proxy_node.cc

This change almost completely removes message related to dropping outgoing speed command for me.
Another improvement can be noticed on the stdout - when the python part outputs something to the console, right after it is also outputed by the c++ part. Before there was a significant delay.

ros_proxy_node: move zmq receive to thread

---

.github/workflows/python-ci.yaml
.travis.yml
osgar/__init__.py
osgar/drivers/realsense.py
osgar/drivers/test_rosproxy.py
requirements.txt
setup.py
subt/artifacts.py
subt/docker/robotika/Dockerfile

Upgrade dependencies.

---

osgar/logger.py

Changes column sizes to actually fit the counts and sizes inside for large logs and added a header row.
Before:
<pre> 0                 sys      14484 |    98 |   0.0Hz
1   app.desired_speed     301564 | 25422 |   9.6Hz
2          app.pose2d    1674800 | 127850 |  48.4Hz
3        app.artf_xyz        276 |     9 |   0.0Hz
4          app.pose3d    8438100 | 127850 |  48.4Hz
5          app.stdout       8507 |    58 |   0.0Hz
6  app.request_origin          1 |     1 |   0.0Hz
7       detector.artf        447 |    20 |   0.0Hz
8    detector.dropped      51088 | 51088 |  19.3Hz
9 detector.debug_artf     535441 |    19 |   0.0Hz
10     detector.stdout       6214 |   114 |   0.0Hz
11   reporter.artf_cmd        396 |     9 |   0.0Hz
12     transmitter.raw          0 |     0 |   0.0Hz
13 …

osgar.logger: cleanup stat output

---

subt/depth2scan.py

Having the functions outside on the main scope makes testing and/or optimizing them easier.

subt.depth2scan: move code around without any changes

---

.github/workflows/python-ci.yaml

... to see which test exactly it gets stuck on.

.github/workflows: run tests verbose

---

osgar/drivers/rosproxy.py

The same problem as was in `rosproxy_test.py:DummyROSMaster` class was also
in `MyXMLRPCServer`. Shutting down the server was not threadsafe and could
stuck (race condition) which resulted in `rosproxy.is_alive() == False`
to fail in tests.

osgar.drivers.rosproxy: fix MyXMLRPCServer shutdown race

---

subt/script/bridge.bash
subt/script/sim.bash

Having the terminal title set makes easier to later find the right tab.

subt/script/{bridge,sim}: set terminal title

---

moon/__init__.py
moon/main.py
moon/test_main.py

Moon rover is using 4WD so "virtual bumper" is not as efficient as it is for passive rear wheels. The terrain is complex but at least hard collision with rock could be avoided.

moon/main.py - provide monitors with an example of LidarCollisionMonitor

---

subt/tools/ignstate.py

Helmet and Rope + some small tweaks. The marker type is reused from
Urban specific artifacts.

Support new Cave artifacts in subt/tools/ignstate.py

---

subt/main.py
subt/test_subt.py
subt/test_trace.py
subt/trace.py

There are no code changes except the movement.

subt: Move Trace to separate file.

---

.github/workflows/python-ci.yaml
subt/simulation.py
subt/test_subt.py

I'd like to eventually improve trace following robustness (taking shortcuts vs getting stuck) and also wall following (to weed out the situations where the robot spins in place, that we have experienced on both real and simulated robots). I'd also like to continue my work on monitors (timeouts and such). For all of that I feel a strong need to have some tests where I can deterministically reproduce the problem.
This is the first step towards that goals.

subt.test_subt: add test_go_to_entrance

---

osgar/tools/lidarview.py

the current implementation does not display the boxes in certain scenarios. This attempts to hook into the process differently in order to show the rectangles reliably

rework insertion of streams of rectangles into the viewer

---

subt/main.py

When not enabled on start, custom output (even from other modules) is not shown.

subt.main: configure python logging

---

moon/controller.py

this line was lost during previous PR merge

fix gimbal, publish instead of req/rep

---

moon/config/moon-excavator-round2.json
moon/config/moon-hauler-round2.json
moon/config/moon-round1.json
moon/config/moon-round3.json
moon/controller.py
moon/controller_excavator_round2.py
moon/controller_hauler_round2.py
moon/controller_round1.py
moon/controller_round3.py
moon/moonnode.py
moon/rospy/rospy_base.py
moon/rospy/rospy_rover.py
moon/vehicles/excavator.py
moon/vehicles/rover.py
moon/vehicles/scout.py
osgar/drivers/rosmsg.py
subt/ros/proxy/ros_proxy_node.cc

So far moon was run in real time which was also sim time. After most recent changes in the simulator, the simulation got substantially slowed down raising need for running in sim time to calculate various timeouts and such correctly.

Convert moon to sim time

---

moon/controller.py
moon/controller_excavator_round2.py
moon/controller_hauler_round2.py
moon/controller_round1.py
moon/controller_round3.py
moon/test_controller.py
osgar/drivers/logzeromq.py

instead of blocking threads by letting them wait for a response to a request, a callback is submitted as an additional argument of the request and thread continues; callback is then invoked with the response as its parameter once available

rework ReqRep framework to use callbacks instead of blocking

---

subt/rosbag2log.py

Since release 2020-07-23 there several new *.yml files + new prefix for logs:
events.yml
run.yml
score.yml
server_console.log
state.tlog
state.tlog-journal
subt_cave_2020-07-29T15_21_00.375726192.log
summary.yml

subt/rosbag2log.py - extract new *.yml and cave report files

---

subt/ros/proxy/ros_proxy_node.cc
subt/ros/proxy/ros_proxy_teambase.cc

The motivation is to avoid collisions with default port used for report
artifacts https://github.com/osrf/subt/issues/502

SubT comm - use for broadcast dedicated port

---

moon/docker/build.bash
moon/docker/rover/Dockerfile
moon/docker/rover/entrypoint.bash
moon/docker/rover/run_solution.bash

Assumes ${HOME}/space-challenge/ folder which contains the following subfolders:
* srcp2-competitors from https://gitlab.com/scheducation/srcp2-competitors/-/tree/master
* openvslam/openvslam from https://github.com/frantisekbrabec/openvslam/tree/subscribe_stereo_camera
* openvslam/orb_vocab/orb_vocab.dbow2 from [here](https://drive.google.com/open?id=1wUPb328th8bUqhOk-i8xllt5mgRW4n84)
* osgar (this)

Build unified osgar+openvslam docker

---

moon/controller_excavator_round2.py
moon/controller_hauler_round2.py

yaw extracted from true pose received by hauler was applied to excavator, not hauler

fix of yaw update

---

moon/docker/rover/Dockerfile

needed to change where docker imports this library from

retrieve eigen library from gitlab

---

requirements.txt
subt/docker/base/Dockerfile
subt/docker/robotika/Dockerfile

For details see particular commits.
Needs testing.

Update base image to include rtabmap + update dependencies

---

subt/cloudsim2osgar.py
subt/docker/robotika/Dockerfile
subt/docker/robotika/run_solution.bash
subt/main.py
subt/ros/proxy/sendlog.py
subt/ros/robot/launch/x4.launch
subt/ros/robot/src/altitude_from_atmospheric_pressure.py
subt/ros/robot/src/drone_height.py
subt/simulation.py
subt/test_subt.py
subt/zmq-subt-x2.json
subt/zmq-subt-x4.json

`rtabmap` is now used as the main source of position instead of OSGAR visual odometry. Also the height is taken into account for navigation on trace. Finally offset is used for left & right wall for more reliable nearest obstacle selection.

Upgrade drone X4 to use rtabmap instead of visual odometry

---

subt/main.py
subt/name_decoder.py
subt/script/bridge.bash
subt/script/sim.bash
subt/simulation.py
subt/test_name_decoder.py

SubT allow wall side change based on the robot name

---

subt/offseter.py
subt/zmq-subt-x4.json

Adds `offseter.pose3d` in global reference frame. Pose validator works again:

subt.offseter: new node to calculate offset to global frame

---

subt/artf_node.py
subt/script/debug-virtual-view.bat

Save depth data at least for detected artifacts for debugging of their distance computation

SubT log artifact debug depth

---

subt/tools/ignstate.py

No change in functionality, just less repetition and smaller functions.

subt.tools.ignstate: refactoring

---

subt/tools/validator.py

validator subsumes more functionality - on the way to become the goto-tool for log validation

subt.tools.validator: also draw ground truth

---

subt/breadcrumbs.py
subt/cloudsim2osgar.py
subt/radio.py
subt/test_breadcrumbs.py
subt/test_radio.py
subt/zmq-subt-x2.json

Hopefully this PR will validate refactoring in #657 i.e. sharing positions of breadcrumbs. It is expected that they are all "online", i.e. the message is not automatically repeated.

Share location of breadcrumbs via radio

---

osgar/tools/lidarview.py

- highlight robot position with different color
- handle missing depth data
- for dump depth.npz insert also image, pose3d and scan
- print heading of the robot instead to reference to start

improve lidarview.py for easier analysis

---

subt/cloudsim2osgar.py
subt/zmq-subt-x2.json
subt/zmq-subt-x4.json

I am still running some local tests but it is ready to review. For me the main question is, how many values do we want/need from http://docs.ros.org/melodic/api/sensor_msgs/html/msg/BatteryState.html? Is percentage enough or do we want something more?

subt.cloudsim2osgar: add score and battery_state

---

subt/ros/robot/src/drone_height.py

Fixes problem with battery being depleted unexpectedly (in a local test run).

subt....drone_height: only publish cmd_vel when started

---

osgar/lib/depth.py
subt/docker/robotika/run_solution.bash
subt/main.py
subt/subt-freyja.json

This is attempt to handle steep places like P3 and narrow places like S2(?) for robot Freyja.

Freyja - modified detection of cliffs/stairs

---

subt/tools/ignstate.py

Adding legend as requested in https://github.com/robotika/osgar/pull/662#issuecomment-705145689

subt.tools.ignstate: add legend

---

subt/main.py
subt/name_decoder.py
subt/test_name_decoder.py

Original code `enter` is not sufficient as `subt/main.py` decided on side where to be closer.  This PR should fix it.

SubT - fix entrance side

---

subt/tools/submit.py

subt.tools.submit: add Cave Circuit

---

subt/script/bridge.bash
subt/script/sim.bash

I am not sure if I am the only one using these script. Anyway, I got tired of specifying "circuit" manually.

subt.script.{bridge,sim}.bash: autodetect circuit

---

osgar/test_zmqrouter.py
osgar/zmqrouter.py

Fix for what most likely happened in https://github.com/robotika/subt-artf/issues/37.

osgar.zmqrouter: increase the timeout on starting to 20s

---

subt/rosbag2log.py
subt/tools/validator.py

Just a minor change to get comparable consistent output among different runs.

rosbag2log,validator: sort logfiles before processing

---

subt/main.py

I just would like to have "separator" for large run from master ...

SubT set release version Ver84

---

subt/artf_reporter.py
subt/artifacts.py
subt/main.py
subt/test_artf_reporter.py
subt/test_artifacts.py
subt/test_subt.py
subt/zmq-subt-teambase.json
subt/zmq-subt-x2.json
subt/zmq-subt-x4.json

This is still WIP, just send artifact data with status=True/False/None ... successfully scored/failed/unknown=not reported yet (or not confirmed report).
Feel free to ignore, while in Draft status

SubT - report artifacts together with source and status

---

osgar/tools/lidarview.py

Extension of lidarview, that for X4 drone in SubT we can see readings from up/down lidars:
I use it in combination with
```
subt\script\virtual-view.bat --lidar-up fromrospy.top_scan --lidar-down fromrospy.bottom_scan  <logfile>
```

lidarview - draw up/down laser values

---

subt/main.py

p.s. I am not sure about Z coordinate?
p.s.2 - motivation:

SubT - increase false detection artifact filter for Cave staging area

---

subt/main.py
subt/simulation.py
subt/test_subt.py
subt/zmq-subt-x2.json
subt/zmq-subt-x4.json

This is the first step to for recovery from position error on start when robot is not moving, but Kalman is able to collect easily 50 meters offset. This solution updates offset as long it is available

subt/main.py - remove dependency on offset for pose3d

---

subt/main.py
subt/test_trace.py
subt/trace.py

Now we use global coordinates, so robot does no longer start from (0, 0, 0).

subt/trace.py - handle variable initial position

---

subt/ros/robot/launch/freyja.launch
subt/ros/robot/launch/x4.launch

Reduce 250Hz IMU messages to 50Hz

SubT - downsample IMU messages

---

osgar/bus.py
subt/artf_node.py
subt/drone.py
subt/main.py
subt/test_drone.py
subt/zmq-subt-x4.json

Calculates desired Z speed directly from current position and target position and maximum speed.

set z-speed directly for return home

---

subt/ros/robot/launch/freyja.launch

It was running at 50Hz while X4 is running at 250Hz. Let's use both at 50Hz.

Undo changes for Freyja IMU

---

subt/main.py

SubT Cave Circuit - release candidate 1

---

subt/drone.py

This should fix https://github.com/robotika/subt-artf/issues/59#issuecomment-709599550 and https://github.com/robotika/subt-artf/issues/58#issuecomment-709611825.

subt.drone: fix sign when EMERGENCY_HEIGHT is hit

---

subt/drone.py
subt/main.py
subt/zmq-subt-x4.json

I did not get suggestions for new parameters, so I am picking "golden middle".

SubT turning parameters

---

subt/tools/ignstate.py

The poses are logged at 250Hz. Most of the time we don't need that much data (in validator we even use 1Hz). Now we can select the hz when calling `read_poses`. In addition `iter_poses` allows iterating over the pose data in `state.tlog` so even custom accumulation strategy can be implemented.
I am suggesting to set the default Hz in ignstate main to 50Hz, which lowers the memory pressure 5x while keeping the resulting picture almost the same.
Fix for #709.
Watch for the red pixels noting the differences.
Diff between 50Hz:
Diff between 20Hz:

Allow for lower rate in read_poses in ignstate

---

subt/cloudsim2osgar.py
subt/zmq-subt-x2.json

This is the first step to support multiple cameras in SubT Virtual. In order to plug it into detector there is also need to get depth data from rear camera. Also position of rear camera has to be "specified somewhere".
Another step is to remove subscribe from `ros_proxy_node.cc` and also Robotika X2 should be moved/fixed.

SubT Freyja front/rear cameras via cloudsim2osgar

---

subt/cloudsim2osgar.py
subt/zmq-subt-x2.json

this is another piece to be removed from `rosmsg.py` - at the moment the data are collected simultaneously and source is still `rosmsg.py`

Freyja front/rear lidar via cloudsim2osgar

---

subt/cloudsim2osgar.py

We can now send even `numpy` arrays which will correctly deserialize on the other end (numpy is already installed for the system python2 interpreter).

subt.cloudsim2osgar: use osgar serialize lib

---

subt/cloudsim2osgar.py

I wanted to fix also freyja.launch but when I do so, rosmsg fails with
some error and since we want to get rid off it anyway, I backed off that
fix.

freyja: use rgbd cameras instead of rgb-only

---

subt/docker/robotika/Dockerfile
subt/docker/robotika/python_logging.conf
subt/docker/robotika/rosconsole.config
subt/docker/robotika/run_solution.bash
subt/ros/robot/launch/x4.launch
subt/script/sim.bash

* robotika/Dockerfile:
- don't redownload dnn files every time
- set ENV to configure logging (rospy + roscpp)
- add convenience top level Makefile soft link
- add convenience top level run_solution.bash soft link
* run_solution:
- remove OMP_NUM_THREADS (moved to base/Dockerfile)
- remove ROSCONSOLE_CONFIG_FILE (moved to robotika/Dockerfile)
* sim.bash: add missing $
* x4.launch: enable ros_proxy_node output to screen

Convenience and maintenance changes.

---

subt/cloudsim2osgar.py

@zwn thanks for pointing this out ...

subt/cloudsim2osgar.py - fix swapped sections for K2 and Freyja

---

subt/tools/run.py

Test with
```
world = "cs1"
timeout = 240
image = "latest"
[robots]
A100L = "drone"
B10W100R = "drone"
```

subt.tools.run: use isolated networks for multiple robots

---

osgar/drivers/rosmsg.py
subt/docker/base/Dockerfile
subt/ros/robot/launch/freyja.launch

- improvement of localization
- octomap for data collection (not used)
- fix of cameras for artifact detection

Freyja localization and mapping

---

subt/main.py

The goal is to score extra point for the backpack in starting area:
https://github.com/robotika/subt-artf/issues/66#issuecomment-719566998

Reduce filter for staging area to be common for Cave and Urban

---

subt/ign.proto
subt/ign_pb2.py
subt/tools/ignstate.py

@tajgr Please take a look. I've fixed the way the sdf world is parsed. Now no more hacks should be needed.

subt.tools.ignstate: parse sdf world as StringMsg

---

subt/artf_gas.py
subt/artifacts.py
subt/config/r2.json
subt/main.py
subt/test_artf_gas.py
subt/test_artifacts.py
subt/zmq-subt-x2.json
subt/zmq-subt-x4.json

There is `ver93gas` running simulation in Urban 1 (`e119ee7f-3f7e-444d-b84f-6307d69edb43`).

Fix gas detection for Urban worlds

---

subt/docker/robotika/Dockerfile
subt/ros/robot/src/laserscan_to_pointcloud.py

added a ros node for conversion of laserscan topic to pointcloud2 -> to be used later for lidar to octomap etc,....

added ros node for conversion of laserscan topic to pointcloud2

---

subt/docker/base/Dockerfile
subt/docker/robotika/Dockerfile
subt/docker/robotika/Makefile
subt/ros/robot/launch/freyja.launch

includes ros-melodic-octomap-server

base image 2020-11-11

---

subt/artf_model.py
subt/artf_node.py
subt/docker/robotika/Dockerfile
subt/main.py
subt/tf_detector.py

- parameters for MDNet training

Extend SubT detector for drill and fire extinguisher artifacts

---

subt/cloudsim2osgar.py
subt/main.py
subt/ros/robot/launch/x4.launch
subt/zmq-subt-x4.json

This is attempt to create ocomap not only for Freyja, but also for SSCI_X4 drone (at the moment only from camera).
It does not work at the moment - `frame_id` for ocomap is probably wrong - any hint?

Integrate octomap for drone X4

---

subt/tools/ignstate.py

@zwn - I can confirm that the fix works, thanks.
```
python subt\tools\ignstate.py d:\logs\aws\finals\ver99octobread2\state.tlog
B120CXM__breadcrumb___0: 29.54 -0.18 2.90
B120CXM__breadcrumb___1: 48.18 -23.50 5.00
B120CXM__breadcrumb___2: 47.93 -43.55 0.00
B120CXM__breadcrumb___3: 47.81 -49.98 0.00
B120CXM__breadcrumb___4: 48.71 -55.65 0.00
B120CXM__breadcrumb___5: 52.43 -59.19 0.00
A60W210LXM__breadcrumb___0: 87.56 -8.27 5.00
A60W210LXM__breadcrumb___1: 116.08 0.60 5.00
min x: -61.50 y: -189.29
max x: 234.81 y: 123.07
width: 3003px height: 3163px
created: d:\logs\aws\finals\ver99octobread2\state.tlog.png
```

subt/tools/ignstate.py - update model parsing

---

subt/ros/robot/launch/freyja.launch

Tested/tuned in Cave Practice 2 as the longest run.

freyja.launch - improved localization (tested in Caves)

---

subt/octomap.py
subt/ros/robot/launch/x4.launch
subt/zmq-subt-x4.json

Extends Freyja functionality also for drone (for a single Z-level equal to 2m)
(Freyja mapped the whole area, but the drone at least tried ...)

Extend planning for X4 drones

---

subt/submission/two-freyjas.toml
subt/tools/submit.py

And modify sample two freyjas config

Add finals practice worlds

---

subt/tools/ignstate.py

Extend ignstate.py to draw Cube artifact

---

subt/cloudsim2osgar.py
subt/config/r2.json
subt/ros/proxy/ros_proxy_node.cc
subt/ros/robot/launch/freyja.launch
subt/ros/robot/launch/k2-virt.launch
subt/ros/robot/launch/r2.launch
subt/zmq-subt-x4.json

This is 2nd step in conversion from rosproxy to cloudsim2osgar

Refactor rosproxy - remove image, depth and lidar scans

---

osgar/lib/depth.py
osgar/tools/lidarview.py
subt/artf_node.py
subt/cloudsim2osgar.py
subt/config/r2.json
subt/depth2scan.py
subt/main.py
subt/ros/robot/launch/freyja.launch
subt/ros/robot/launch/k2-virt.launch
subt/ros/robot/launch/r2.launch
subt/subt-freyja.json
subt/subt-k2-virt.json
subt/test_artf_node.py
subt/test_depth2scan.py
subt/zmq-subt-x2.json
subt/zmq-subt-x4.json

The output of simulated RGBD cameras is available in different ROS topic although they refer to the same device sensing the world at the same time. This PR provides solution to keep the bundled and adds also information about robot global position and relative camera position. It simplifies synchronization in later stage when for example we want to report global position of newly detected artifact in camera image. Moreover it opens a way to handle artifact positioning from different robot views. Finally it allows detection and reporting artifacts from rear cameras of Freyja, K2 and R2.

Synchronized RGBD data stream

---

subt/cloudsim2osgar.py
subt/config/r2.json
subt/main.py
subt/marsupial.py
subt/ros/proxy/ros_proxy_node.cc
subt/simulation.py
subt/test_marsupial.py
subt/zmq-subt-x2.json
subt/zmq-subt-x4.json

After this PR origin is no longer needed in OSGAR SubT part. There is only exception of old localization used for Explorer R2, which will be handled separately.

Remove dependency on origin and use only robot_name

---

subt/config/r2.json
subt/depth2scan.py
subt/zmq-subt-x2.json
subt/zmq-subt-x4.json

I am going to test this new filter on CloudSim (ver102fog) in Finals Practice 1. (`6ffa291e-18b2-480d-91a5-a18ee5ab9312`)

Filter fog in depth2scan

---

subt/docker/robotika/Dockerfile
subt/tf_detector.py

The new tf model contains also the tenth artefact cube. Note, there is not update for mdnet yet.

Update subt detector, cube

---

osgar/explore.py
subt/config/r2.json
subt/depth2scan.py
subt/main.py
subt/subt-freyja.json
subt/zmq-subt-x2.json
subt/zmq-subt-x4.json

Attempt to improve navigation in tunnel and urban worlds where Freyja was falling into vertical shafts.

Improve avoidance of steep drops/vertical shafts for Freyja

---

osgar/explore.py
osgar/lib/depth.py
osgar/lib/loop.py
osgar/lib/quaternion.py
subt/cloudsim2osgar.py
subt/depth2scan.py
subt/main.py
subt/ros/robot/src/k2.py
subt/subt-freyja.json
subt/subt-k2-virt.json
subt/zmq-subt-x2.json

Use robot symmetry for "turns" in narrow corridor (replaced by flips). This PR primarily address Freya and partially Kloubak K2. R2 is on TODO list.

Use symmetry of robots in Virtual World

---

subt/cloudsim2osgar.py
subt/push.py
subt/zmq-subt-x4.json

This is the first attempt to directly control drones `cmd_vel` via `rospy` (`cloudsim2osgar.py`). If you will like this PR, then the next step would be extension also for ground vehicles.

Control drone speed via rospy

---

subt/cloudsim2osgar.py
subt/test_twistwrap.py
subt/twistwrap.py
subt/zmq-subt-x2.json

This is follow up PR of #800 extending ROS Twist rospy way also for ground vehicles (now for Freyja).

Control speed for Freyja via rospy

---

subt/tools/ignstate.py

subt/tools/ignstate.py - extra except for protobuf error parsing

---

subt/artf_node.py
subt/docker/base/Dockerfile
subt/docker/robotika/Dockerfile
subt/main.py
subt/tf_detector.py

Note, that new robotika base image is necessary to build and upload to dockerhub.

OpenCV Python compiled to run on GPU

---

subt/artf_node.py
subt/test_artf_node.py
subt/tools/analyze_detectors.py

There is new tool which could be used for threshold setting of our detectors. Only ver0 for this moment

Analyze detectors

---

config/test_system-monitor.json
config/test_system_monitor.json
osgar/drivers/__init__.py
osgar/drivers/system_monitor.py

Records system information like CPU and RAM utilization or device temperatures.
TODO log dmesg

Logging CPU load, temperature, ram

---

subt/artf_node.py
subt/cloudsim2osgar.py
subt/config/coro_pam.json
subt/docker/robotika/run_solution.bash
subt/drone.py
subt/main.py
subt/ros/proxy/CMakeLists.txt
subt/ros/proxy/flyability.cc
subt/ros/robot/launch/coro_pam.launch

This is follow up of already merged PR #829 with tuning of CoRo drone + introduction of new module for drones "flyability" (similarly as "traversibility" was for ground vehicles).

Introduce "flyability" package for CoRo drone

---

subt/submission/finals.toml
subt/tools/submit.py

I am still not sure about the official "finals" name :( ... it was not release AFIK??
the reference run is:
`3d2d20e3-1185-4641-b278-599c25044357`

Add SubT configuration for Finals

---

osgar/explore.py
osgar/lib/virtual_bumper.py
osgar/tools/lidarview.py
subt/config/coro_pam.json
subt/docker/robotika/run_solution.bash
subt/main.py
subt/ros/proxy/traversability.cc
subt/submission/finals.toml
subt/subt-freyja.json
subt/zmq-subt-x2.json

reference run `ver113follow`, `13797cc4-056f-41de-88e3-adeca5d63a57` in UC7

Improve follow wall and tune parameters

---

subt/cloudsim2osgar.py
subt/config/coro_pam.json
subt/main.py
subt/ros/robot/launch/coro_pam.launch
subt/ros/robot/launch/freyja.launch
subt/ros/robot/launch/k2-virt.launch
subt/ros/robot/src/origin_tf.py
subt/zmq-subt-x2.json

reference run FP1 - `ver116map` - `b41de283-c65a-4c03-9c01-e9790076b775`

Mapping server - ver0

---

subt/tools/draw_pos_data.py

and also interactive slidebar to see situation in given time.
Example video of test in FP1 is here:
https://youtu.be/6PqRUhDVGFU

Extend draw_pos_data.py to create video

---

osgar/explore.py
subt/main.py

Mainly for blind spot of Freyja to the side
Reference docker image `ver119narrow`

Avoid narrow corridors

---

subt/drone.py
subt/main.py
subt/test_drone.py

Reference image `ver121stairs`, FP2 run two drones left/right (`56cb9ae1-69e5-45d7-8d25-1492730d9049`)

Handle return via narrow stairs up

---

subt/tools/validator.py

the z-error seems to be fine, just validator needs this minor fix, thanks m.

Fix relative import in subt/tools/validator.py

---

subt/main.py

I would increase version after #862

subt/main.py - set Ver122

---

subt/main.py
subt/ros/proxy/flyability.cc
subt/ros/proxy/traversability.cc
subt/ros/robot/launch/freyja.launch
subt/script/bridge.bash
subt/script/sim.bash
subt/subt-freyja.json

(and minor fix to support both finals and final_prelim worlds)

Handle narrow passages and doors

---

subt/ros/robot/launch/x4.launch
subt/ros/robot/src/filter_pointcloud.py
subt/ros/robot/src/origin_tf.py
subt/ros/robot/test/test_filter_pointcloud.py
subt/zmq-subt-x4.json

I am not sure if to merge it before finals as it is also influencing Pam code ... but Pam is default, so maybe there is no issue. Thanks!

Support drone X4 again

---

subt/tools/artf2json.py

The output can be like:
which is the case Freyja is stuck on the rail but it still tries to compute stereo -> generates many false artifacts

Extend subt/tools/artf2json.py to support images from mono cameras

---

subt/artf_detector.py
subt/artf_node.py
subt/tf_detector.py

This PR try to reflects false detections in FPR3 (email discussion)

Detectors borders modification

---

subt/artf_node.py
subt/subt-freyja.json

so that both left and right, front and rear cameras are processed.
There is typically some random order at the beginning but shortly
the inputs are regularly interlaced.

Handle Freyja detections in batches

---

subt/main.py

make sure that scan and pose3d are available before any action ... (although the plan now is to unify System and Virtual)

subt/main.py - wait for critical data (scan, pose3d) also in System

---

config/kloubak2-subt-estop-lora-jetson.json
osgar/drivers/lord_imu.py
subt/odoimuloc.py
subt/test_odoimuloc.py

There is a need to have some `pose3d` and old code for Virtual can do it. Note that LORD uses different quaternions order

Recover odoimuloc for K2 system backup

---

config/kloubak2-subt-estop-lora-jetson.json
config/test-wifiscan.json
subt/wifisignal.py

It should solve problem with different interface name on robots.

Wifi scan - parametric name of interface

---

subt/mapping_server.py
subt/test_mapping_server.py

This is the simplest version reporting only empty map. The server is running locally in docker (with RViz).
```
(osgar) md@md-ThinkPad-P50:~/git/osgar$ python subt/mapping_server.py --token FKDzKcNTugczqkpC --loop
-> Sending message of size 119
<Response [200]>
-> Sending message of size 119
<Response [200]>
-> Sending message of size 119
<Response [200]>
-> Sending message of size 119
<Response [200]>
-> Sending message of size 119
<Response [200]>
-> Sending message of size 119
...
```
issues:
- `cbor` (binary JSON) is not part of requirements.txt (patch unittest?)

SubT mapping server ver0

---

config/test-apriltag-rs.json
osgar/drivers/realsense.py
subt/apriltag.py
subt/bundle_rgbd.py

Ver0 of the apriltags detector. <s>It use @zwn  fork https://github.com/zwn/apriltag.git</s>
https://robotika.cz/articles/reviews/apriltag/cs/
It is too late so probably some adjustments tomorrow.

Detect apriltags

---

subt/mapping_server.py

I had to switch to Kloubak K2 and tweak it to support reporting ... and it could be actually used for detection if the log is from K2 or Skiddy.

Allow report of map for both Skiddy and Kloubak

---

subt/tools/submit.py

it is not working yet :( ... and we have to leave for testing ...
```
(osgar) md@md-ThinkPad-P50:~/git/osgar$ python subt/tools/submit.py subt/submission/two-pams.toml
world:   Final Prize Round World 8
image:   138467776890.dkr.ecr.us-east-1.amazonaws.com/subt/robotika:ver133
simname: ver133fr8r1
robots:  
A600L: CORO_PAM_SENSOR_CONFIG_1
B10W600R: CORO_PAM_SENSOR_CONFIG_1
T1400: TEAMBASE
{
"errcode": 3013,
"msg": "Invalid value in field.",
"extra": [
"Circuit:Final Prize Round World 8"
],
"errid": "ff62aa94-728f-4563-a70a-f9ed7044d5e1",
"route": "POST /1.0/simulations",
"user-agent": "",
"remote-address": "75.81.238.15"
}
```

Add SubT finals virtual worlds

---

config/eduro.json
osgar/followme.py

Update base Eduro config and followme app

---

config/spider-velodyne.json
config/spider.json
config/test-eth-gps.json
config/test-spider.json
examples/demo/spider_demo.py
osgar/drivers/canserial.py
osgar/drivers/gps.py
osgar/drivers/spider.py
osgar/drivers/test_spider.py

This PR follows up the older branch (feature/spider-robotour). Implements new encoders.

Spider encoders

---

config/gps-pozyx.json
config/test-pozyx.json
osgar/drivers/__init__.py
osgar/drivers/pozyx.py

Pozyx devices (anchors and tags) use UWB (ultra wide band) technology for short range communication and localization. For more info see https://robotika.cz/articles/pozyx/cs
This is the very first attempt (now almost year old), which I would merge and continue with development for ELROB 2024.

Pozyx driver

---

config/spider-camera.json
osgar/drivers/spider.py
osgar/go.py

This is first version (after a while) which was sufficient to drive Spider autonomously (with Car mode as "pause"). The next needed step is proper speed control based on encoder values, which will be separate PR.

Spider move and extend go.py

---

config/spider.json
osgar/drivers/spider.py

There is an implementation of basic Spider steering. This PR may allow to Spider basic autonomous movement.

Spider steering

---

config/eduro-followme-vanjee.json
config/eduro-go-vanjee.json
osgar/drivers/vanjee.py
osgar/followme.py
osgar/lib/icp.py
osgar/lib/test_icp.py

VanJee lidar (4 layers, 360deg) was tested on robot Eduro with precise odometry. Simple `go` and `followme` are now supported. Also the first attempt to understand ICP is implemented (but will require serious revision)

Support VanJee lidar on Eduro

---

osgar/go.py

`python -m osgar.record config/eduro-go.json --params app.repeat=5 app.dist=-1.0` ... i.e. repeat motion backward, forward, backward, forward, backward ...
Yes, the motivation is robot Pat and really small maneuver place +/-20cm so I need to repeat it enough times to give OAK-D time to start ...

Add option "repeat" for osgar.go

---

config/test-oak-camera.json
osgar/drivers/oak_camera.py

Add manual exposure time option for color camera.

oak - manual exposure time for color

---

osgar/drivers/vanjee.py
osgar/followme.py
osgar/followpath.py

These are some "tweaks" from ELROB to force robot Pat to followme with VanJee lidar. See 
https://youtu.be/1zBAZVKO0kE
for reference.
There is also new draw functionality for quick overview given run, for example:

Improve follow me (used on robot Pat)

---

config/matty-go.json
osgar/followpath.py
osgar/platforms/matty.py
osgar/platforms/test_matty.py
osgar/tools/map3dview.py

This branch was originally development for DTC Systems Workshop 2 ... which ended yesterday (without Matty) so it makes sense to merge what we discovered over the preparation period. In particular bugfix related to multiple messages in one data buffer is critical.

Matty upgrade and bugfixes

---

config/test-oak-camera.json
osgar/drivers/oak_camera.py

Adds option to alignment depth and color frame. 
https://docs.luxonis.com/software/depthai/examples/rgb_depth_aligned/

Depth and color aligment for oak-d cameras

---

osgar/drivers/spider.py

I'm probably driving too fast. The original value was probably set for autonomous mode, which is slower.
I'll check the maximum speed values ​​tomorrow.

ENC limit for spider is too low

---

osgar/drivers/oak_camera.py
osgar/drivers/test_oak_camera.py

tested on road detection - TODO clean up after RORO25

Support Neural Networks with bitmask output

---

.github/workflows/python-ci.yaml
osgar/tools/lidarview.py

At the moment we are using various models for detection in FRE2025 project. Some are square like 640x640 some are "landscape" like 640x352. This PR is to enable more-or-less correct visualization in lidarview.

Support different detection NN box scaling in lidarview

---

osgar/tools/lidarview.py

Just simple modification to improve readability.

Add label to bbox in lidarview

---

config/test-audio.json
osgar/drivers/audio.py
osgar/tools/log2wav.py

This will bring audio support (recording for now) to OSGAR. The code was written by Helena, including sketch of configuration, my minor input was test on win11 and Odroid H4+, and fix of single line.
Besides driver also conversion tool to WAV files is implemented.
(note, the proper test on Odroid is pending due to missing HW)

add Audio driver
